### ISSUE TITLE
[FEATURE] Filter based on custom properties x-*

### ISSUE THREAD

**Issue by niecore** [schemathesis/schemathesis#1006]
**Is your feature request related to a problem? Please describe.**
I transform my API Description from `raml` to OpenAPI3 and therefore can not make the use out of tags.
The only way to mark operations with custom information is via the `vendor extension` (https://swagger.io/docs/specification/openapi-extensions/)

**Describe the solution you'd like**

It would be helpful if I could filter tested operation by a list of `vendor-extensions`.

`--vendor-extension x-test true --vendor-extension x-imaginary false`

**Comment by Stranger6667** [comment]
Hi @niecore !

Cool idea! I was planning to refactor all the filtering code in the next few weeks and definitely will think about filtering by vendor extensions :) Could you please share an example of the schema that you have after transformation? I assume that you have `x-*` extensions on the individual items in `paths`?

**Comment by niecore** [comment]
Yes, exactly:

`
openapi: 3.0.0
info:
  title: api
  version: 1.0.0
servers:
  -
    url: http://localhost:8081
paths:
  /gateway:
    patch:
      responses:
        "403":
          description: ""
    x-example-one: true
    x-example-two: false

`
