### ISSUE TITLE
[BUG] Schemathesis can no longer serialize `text/yaml` media types

### ISSUE THREAD

**Issue by john-odonnell** [schemathesis/schemathesis#1010]
**Describe the bug**
Upon updating to `3.0.0`, I started getting an error that I didn't get on `2.8.5`. Using the CLI.

```
Can't serialize data to `text/yaml`. You can register your own serializer with `schemathesis.serializers.register` and Schemathesis will be able to make API calls with this media type.
See https://schemathesis.readthedocs.io/en/stable/how.html#payload-serialization for more information.
```

Looking further, I'm not sure `test/yaml` is a legitimate [MIME/Media Yype](https://www.iana.org/assignments/media-types/media-types.xhtml), so I would understand if serialization was not supported.

**To Reproduce**
1. Describe a requestBody as having `text/yaml` content
2. Run Schemathesis

The Spec I'm working on is in [this repo](https://github.com/cyberark/conjur-openapi-spec).
There is a script to run Schemathesis: `./bin/api_test`

If possible, please post a minimal version of your API schema that cause this behavior:

```yaml
{
    "openapi": "3.0.2"
    ...
    components:
      paths:
        Policies:
          put:
            tags:
            - "policies"
            operationId: "loadPolicy"
            parameters:
            - name: "account"
              in: "path"
              required: true
              schema:
                $ref: 'openapi.yml#/components/schemas/AccountName'
            - name: "identifier"
               in: "path"
              required: true
              example: "root"
              schema:
                $ref: 'openapi.yml#/components/schemas/ResourceID'
            requestBody:
              description: "Policy"
              required: true
              content:
                text/yaml:
                  schema:
                    $ref: '#/components/schemas/Policy'
}
```

**Expected behavior**
If I run Schemathesis on my spec with `2.8.5`, this error doesn't occur, and all tests pass.

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - Python version: 3.8.5
 - Schemathesis version: 3.0.0
 - Spec version: OpenAPI 3.0.0

**Additional context**

**Comment by Stranger6667** [comment]
Hi @john-odonnell!

Thank you very much for reporting this! In `3.0.0`, serialization behavior became explicit, and we need a separate serializer for this media type. In `2.8.5`, it was working by coincidence - it was serialized as JSON, which is a valid YAML. However, Schemathesis used `application/json` as the `Content-Type` header value, which doesn't match the media type defined in the schema. This behavior led to weird bugs like this [one](https://github.com/schemathesis/schemathesis/issues/850).

Anyway, the fix will be straightforward - a new serializer for YAML media types. I will use the following ones - `text/yaml`, `text/x-yaml`, `application/x-yaml` and `text/vnd.yaml` :)

**Comment by Stranger6667** [comment]
Support for YAML serialization is released in `3.0.1`. Let me know if it works for you :)

**Comment by Stranger6667** [comment]
As a side note - it doesn't seem that there is an official media type for YAML :( There is [a proposal](https://mailarchive.ietf.org/arch/msg/media-types/e9ZNC0hDXKXeFlAVRWxLCCaG9GI/), though

**Comment by john-odonnell** [comment]
@Stranger6667 Thank you! Works like a charm :)

**Comment by Stranger6667** [comment]
I am delighted to hear that! :)
