### ISSUE TITLE
Publish Docker container to Docker hub using python:3.9.1-buster as base image

### ISSUE THREAD

**Issue by stishkin** [schemathesis/schemathesis#1028]
Currently Schemathesis is published using Alpine as base image.
**Is your feature request related to a problem? Please describe.**
Running MSAL authentication on Alpine is not supported out of the box. On the other hand MSAL works quite well using Buster.

**Describe the solution you'd like**
Publish another (besides alpine) docker image using python:3.9.1-buster as base image

**Describe alternatives you've considered**
Currently we use Buster Linux image and then doing pip install of Schemathesis

**Additional context**
This request to improve integration with [RAFT](https://github.com/microsoft/rest-api-fuzz-testing)

**Comment by Stranger6667** [comment]
Hi @stishkin !

Thank you for bringing this up! I will take a look at it this week :)

**Comment by Stranger6667** [comment]
Hej @stishkin !

The following Buster-based images are available now on Dockerhub:

- `schemathesis/schemathesis:latest-buster`
- `schemathesis/schemathesis:stable-buster`
- `schemathesis/schemathesis:v3.0.7-buster`

Let me know if it doesn't work for you :)
