### ISSUE TITLE
[BUG] Generated Python code samples may be syntactically invalid

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#1030]
**Describe the bug**
Schemathesis may generate a syntactically invalid code sample due to unescaped single quotes in the URL.

**To Reproduce**
1. Run schemathesis against httpbin - `schemathesis run https://httpbin.org/spec.json --validate-schema=false -E status -M PUT --code-sample-style=python`
2. See the following code for `PUT /status/{codes}` (or a similar one)

```
Run this Python code to reproduce this failure: 

    requests.put('http://0.0.0.0:33541/status/{'': {'': None}, '0': None}', headers={'User-Agent': 'schemathesis/3.0.8'})
```

The underlying issue is that the API schema has a very loose definition for this path parameter - it allows JSON objects, arrays, etc.

**Expected behavior**
Any code generated by Schemathesis should be syntactically valid

**Implementation notes**:
- In `Case.get_code_to_reproduce` we need to escape single quotes inside `kwargs["url"]` [here](https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/models.py#L223)

**Comment by leandronogSS** [comment]
I would like pick up this issue. Could you assign it to me? 😄

**Comment by leandronogSS** [comment]
Is the example really correct? 🤔 
![Captura de Tela 2021-10-01 às 10 59 49](https://user-images.githubusercontent.com/45565061/135632801-b1026cf4-aa93-45f7-a05e-6039ab99716b.png)

**Comment by Stranger6667** [comment]
The generated example is not correct, indeed. The solution should be to escape single quotes there

**Comment by leandronogSS** [comment]
I decided to release a problem, thank you

**Comment by Stranger6667** [comment]
Sure! Thanks for taking a look :)
