### ISSUE TITLE
[BUG] Schemathesis follows relative paths if an URL parameter is ".."

### ISSUE THREAD

**Issue by donotnoot** [schemathesis/schemathesis#1036]
**Describe the bug**

Schemathesis seems to be resolving relative paths.

e.g. for an endpoint `/test/{a}`, where `a = ".."`, Schemathesis accesses `/`.

**To Reproduce**

Using

```yaml
openapi: 3.0.0

info:
  title: test
  description: test
  version: 0.0.1

paths:
  '/test/{param}/test2':
    get:
      parameters:
        - in: path
          name: param
          schema:
            type: string
            enum: [".."]
          required: true
      responses:
        '200':
          description: desc
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                properties:
                  status:
                    type: string
                    enum: ["ok"]
                

```

as `bug.yaml`, if you run

```
schemathesis run ./bug.yaml --base-url http://localhost:8080
```

it will make this request

```
% nc -l -p 8080
GET /test2 HTTP/1.1
Host: localhost:8080
User-Agent: schemathesis/3.1.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
```

which is wrong, I guess.

**Expected behavior**

I would expect Schemathesis to call `/test/../test2` literally.

**Environment (please complete the following information):**
 - OS: `Linux 5.9.0-5-amd64 #1 SMP Debian 5.9.15-1 (2020-12-17) x86_64 GNU/Linux`
 - Python version: 2.7.18 or 3.9.1+ (no idea which one actually is used, sorry)
 - Schemathesis version: 3.1.0
 - Spec version: See the file.

**Additional context**

The example is kinda silly as having that enum is ridiculous, but this actually
happened when Schemathesis tried `..` as one of the fuzz-testing patterns for
the URL param.

**Comment by Stranger6667** [comment]
Hi @donotnoot 

Thank you for reporting! I will take a look during the weekend. At the first glance, it seems like we are not escaping these values and they are passed to the underlying `requests` library as-is.

**Comment by donotnoot** [comment]
hey @Stranger6667, thanks for the quick response and for looking into this! Hope debugging it is not too hard :)

**Comment by Stranger6667** [comment]
The fix is released in `3.1.2`. Now `.` and `..` are percent-encoded when Schemathesis generates them for path parameters.

**Comment by donotnoot** [comment]
Amazing, thank you @Stranger6667 :)

**Comment by Stranger6667** [comment]
You're very welcome! :)
