### ISSUE TITLE
Rercursion in Stateful Testing

### ISSUE THREAD

**Issue by mnlpf** [schemathesis/schemathesis#1133]
Hi,
I am trying to do stateful testing with **recursion limit 4**.
Sometimes in testing I can see the recursion level goes only upto the level of 2 or 3. 
As in below example, you can see the recurssion level has gone only till one level.
![image](https://user-images.githubusercontent.com/31038100/115151835-ef813080-a06e-11eb-8b5a-0c99d629c28d.png)

In the below image you will be able to see that the recursion level goes upto level 4
![image](https://user-images.githubusercontent.com/31038100/115151911-471f9c00-a06f-11eb-869d-12600f2aaa5a.png)
_P.S: This is just a part of the execution_

The scehma & the settings both the time were same.
Can you inform what would be the reason for variation in the recursion levels in different execution?
Thank You!!!

**Comment by Stranger6667** [comment]
Hi!

Thanks for asking :) This config option limits the maximum depth, but the stateful testing doesn't guarantee that all generated sequences will reach that depth. Sometimes, the tested app doesn't respond with status codes needed to go to the next level. So the expected depth is less or equal to `stateful-recursion-limit`.

Let me know if that clarifies the observed behavior :)

**Comment by mnlpf** [comment]
Hi,
Thank you for the clarification. 
It is clear that other than the response code there is no other reason for the expected depth to not be met.

**Comment by chaitubits** [comment]
Not sure if this is the right place to ask but I am unable to get stateful testing to work with PyTest . Does it work with PyTest or does just work in CLI for now ?

**Comment by Stranger6667** [comment]
> Does it work with PyTest

Yes, it works with pytest. Did any steps mentioned in [the docs](https://schemathesis.readthedocs.io/en/stable/stateful.html#minimal-example) help? If not, then I'd appreciate a minimal schema example so I can debug it
