### ISSUE TITLE
[BUG] add_case hook not being called

### ISSUE THREAD

**Issue by DavidFarago** [schemathesis/schemathesis#1163]
**Describe the bug**
Using schemathesis, version 3.6.4, the `add_case` hook is never called. following code does not assert false, i.e. the hook is not called:
```
@schemathesis.hooks.register
def add_case(context: hooks.HookContext, case: Case, response: GenericResponse) -> Optional[Case]:
    assert False 
    return None
```
Is this a functional bug or just some documentation missing (or overlooked by me)? 

Switching to a different scope for the hook yields an error.

To print each generated test case, I am now using
```
@schemathesis.hooks.register
def before_generate_case(context, strategy):
    def print_case(case):
        op = context.operation
        print(f'{op.method} {op.path} {case}')
        return case

    return strategy.map(print_case)
 ```
and that hook works smoothly.

**To Reproduce**
1. `pytest -s main.py`
with `main.py` containing:
```
from hypothesis import settings
from hypothesis import strategies as st
import schemathesis
from schemathesis import Case, GenericResponse, hooks
from schemathesis.checks import not_a_server_error
from typing import Optional

# some schemathesis.register_string_format(...)

schema = schemathesis.from_path('../../openapi2.yaml', base_url='http://127.0.0.1:8088')

@schemathesis.hooks.register
def add_case(context: hooks.HookContext, case: Case, response: GenericResponse) -> Optional[Case]:
    print('this is never printed')
    return None

@schema.parametrize()
@settings(max_examples=10)
def test_api(case):
    response = case.call()
    case.validate_response(response, checks=(not_a_server_error,))
```

2. Program executes successfully, `assert False` is never reached.

**Environment (please complete the following information):**
 - OS: Ubuntu 19.04
 - Python version: 3.8.8
 - pytest 6.2.3
 - Schemathesis version: 3.6.4
 - Spec version: Open API 3.0.0

**Comment by Stranger6667** [comment]
> Is this a functional bug or just some documentation missing (or overlooked by me)?

The `add_case` hook works only in CLI, but the documentation misses it :(

**Comment by Stranger6667** [comment]
I added a note on the `add_case` hook scope to the docs in c5e5770202b94dd8759b875cb436c4668c08aa1f

Let me know if you have any questions on the hook system (or if you miss some feature there) :)
