### ISSUE TITLE
[FEATURE] not_a_server_error check should output python request to reproduce bug when server is not responding

### ISSUE THREAD

**Issue by DavidFarago** [schemathesis/schemathesis#1164]
**Is your feature request related to a problem? Please describe.**
My server is running and serving requests, but some specific, reproducible call `c` is not being answered. The server keeps running and serving following requests, but `c` is never answered. Using the following code, schemathesis hangs in some OS routine or in `_read_status` in the `http` client (used by `requests`).
```
@schema.parametrize()
@settings(max_examples=10)
def test_api(case):
    response = case.call()
    case.validate_response(response, checks=(not_a_server_error,))
```
Switching to `response = case.call(timeout=10)` makes `requests` time out and schemathesis no longer hangs. But for `c`, schemathesis does not output a python request to reproduce the bug of the server not responding to the request. 

**Describe the solution you'd like**
The `not_a_server_error` check should output a counter example when the server accepts a request but never responds to it. This could either be with a default timeout, or only when a timeout argument is passed as in the example above. 

**Describe alternatives you've considered**
Outputting all generated requests using `before_generate_case` hook works as workaround.

**Additional context**
    OS: Ubuntu 19.04

    Python version: 3.8.8

    pytest 6.2.3

    Schemathesis version: 3.6.4

    Spec version: Open API 3.0.0

**Comment by DavidFarago** [comment]
Might some hypothesis argument (`timeout`, `deadline`) be a solution to this problem?

Nonetheless, catching the timeout exception from `requests` and handling it would make more sense for me when calling `case.call(timeout=10)`.

**Comment by Stranger6667** [comment]
> Might some hypothesis argument (timeout, deadline) be a solution to this problem?

The problem is that `call` blocks and the Hypothesis machinery might detect it as `DeadlineExceeded` only when `call` returns. So, the `deadline` config option won't cover hanging requests, but a default `timeout` should do the trick. I think that 10 seconds might be a good default value to prevent hanging requests.

**Comment by Stranger6667** [comment]
The `3.7.0` release has the default deadline of 10 seconds. All network requests exceeding this deadline will cause the test to fail (in Python & CLI).

Let me know if it doesn't solve your use case.
