### ISSUE TITLE
[FEATURE] Support colored output from docker container

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#1170]
By default, Click autodetects support for ANSI color codes. In the case of running from Docker (e.g., the default Schemathesis image), colors will be absent. It might be nice to have an option like `--force-color` to force colored output, especially if the end-user knows that the host's terminal supports colors. This option should not be compatible with `--no-color` and if both are passed then we should have an error

**Comment by mohebmithani** [comment]
Hey @Stranger6667 can i take this up for hacktoberfest?

**Comment by Stranger6667** [comment]
Absolutely!

**Comment by mohebmithani** [comment]
Hi @Stranger6667,
I'll start working on this from tomorrow. If you can give some pointers like where to start/look, or how to test this, that would be helpful. Thanks

**Comment by mohebmithani** [comment]
@Stranger6667  I've added a PR, please review it and let me know if any changes are needed

**Comment by Stranger6667** [comment]
Hi @mohebmithani 

Thank you so much for your PR and sorry for the delay - was traveling :) I'll check the PR as soon as I can, likely over the weekend
