### ISSUE TITLE
Sending body parameters in make_case

### ISSUE THREAD

**Issue by Regala** [schemathesis/schemathesis#1188]
Hi! I'm trying out schemathesis and am very new so please apologize the noobness 😊 

I'm running into problems testing `POST` based requests, as the body parameters don't seem to be sent?

So e.g. I'm using https://petstore3.swagger.io as the schema: 

and from python doing:

```
>>> import schemathesis
>>> schema = schemathesis.from_path("pet.json", base_url="http://localhost:8000")
>>> case = schema['/pet']['post'].make_case(body={"blah":1})
>>> case.call()
```

I'm expecting the body should contain the `blah` key but alas, the request body is empty:

![image](https://user-images.githubusercontent.com/1380527/120011049-c771df00-bfd5-11eb-897a-0a350a9a3ca5.png)

Am I missing something?

(screenshot is from a simple simplehttpserver logger)

**Expected behavior**
The `blah` key should be sent on the request body.

**Environment (please complete the following information):**
 - OS: Mac OSX
 - Python version: 3.9.4
 - Schemathesis version: 3.7.3

Thanks!

**Comment by Stranger6667** [comment]
Hi!

Thanks for reporting! You need to specify the proper `media_type` value, in this case, `application/json`. Unfortunately, this part is not much documented, there is already a tracking issue to improve the behavior and avoid silently ignoring explicit payloads without media types - https://github.com/schemathesis/schemathesis/issues/1094

**Comment by Regala** [comment]
Oh!! So would I be able to set that directly in the `.make_case`?

e.g. 
`case = schema['/pet']['post'].make_case(body={"blah":"1"},media_type="application/json")`

**Comment by Regala** [comment]
Humm I'm getting a `TypeError` though:

![image](https://user-images.githubusercontent.com/1380527/120015935-deb3cb00-bfdb-11eb-8b38-ce50457f6221.png)

```
>>> case = schema['/pet']['post'].make_case(body={"blah":"1"},media_type="application/json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: make_case() got an unexpected keyword argument 'media_type'
```

Source code seems to accept it:
![image](https://user-images.githubusercontent.com/1380527/120016164-29cdde00-bfdc-11eb-812c-c3b858b5d44c.png)

**Comment by Regala** [comment]
So for some reason the constructor is not accepting it, but if we do:
```
case.media_type = "application/json"
case.call()
```
it works fine 👌

However I am now stuck, since what I am trying to do is
1) Have schemathesis read the request body format and allow me to pass variables to be filled in (like with `path_parameters`; so in this case I would pass e.g. `id`, `name`, etc)  
2) Have schemathesis read the example from this endpoint (provided in this open API definition)

I thought that for 2) it would be enough to do 
>>> case = schema['/pet']['post'].make_case()
>>> case.body = schema['/pet']['post'].body[0].definition # application/json is the first one defined
>>> case.media_type = 'application/json'
>>> case.call()

Regardless it's the 1) case that I'm looking to do. @Stranger6667 wondering if you can help on this? If this is not the most appropriate venue for these discussions just lmk 😊

**Comment by mbiuki** [comment]
## 1)
> Have schemathesis read the request body format and allow me to pass variables to be filled in (like with path_parameters; so in this case I would pass e.g. id, name, etc)

This seems to be working for me, so you might want to imitate it:

```python
import os
import sys
import json
from hypothesis import strategies as st
from hypothesis import settings, Phase
import schemathesis
import pytest
import jsbeautifier
from datetime import timedelta # For max-response-time
from cachetools import cached, LRUCache, TTLCache
...
schema = schemathesis.from_path( openApiFilePath,
                                 skip_deprecated_operations=True,
                                 validate_schema=True,
                                 code_sample_style="curl",
                                 base_url=URL)
...
@pytest.fixture(scope="session")
def token_getter():
    # The best way to solve it is to call a TTL-cached version of 
    # the printToken function inside test_api.
    @cached(cache=TTLCache(maxsize=1,ttl=int(token_refresh_interval) - THRESHOLD))
    def retrieve_token():
        return printToken()

    return retrieve_token

# mutates global state
schemathesis.register_string_format("uuid", st.uuids().map(str))

@schema.parametrize()
@schema.given(data=st.data())
def test_api(data, case, token_getter):
    token = token_getter()
    case.headers = case.headers or {}
    case.headers["Authorization"] = f"Bearer {token}"
    case.headers["X-KLM-ID"] = X_KLM_ID
    # the following are samples and must not be used, provide your own body fixed ids
    case.path_parameters["personId"] = "<your fixed uuid body params go here>"
    case.call_and_validate()
```


You should run the above code with `pytest` command, e.g., `pytest above_code.py`

## 2)
> Have schemathesis read the example from this endpoint (provided in this open API definition)

Yes, it does, you can look [here ](https://github.com/schemathesis/schemathesis/issues/1158) for more discussion.

**Comment by Stranger6667** [comment]
> TypeError: make_case() got an unexpected keyword argument 'media_type'

It was added in Schemathesis `3.1.0`. This behavior can be observed in older versions. What is the value of `schemathesis.__version__` in your case?

> Have schemathesis read the request body format and allow me to pass variables to be filled in (like with path_parameters; so in this case I would pass e.g. id, name, etc)

It is indeed similar to what @mbiuki provided! You have to do it manually. In Open API 3, request payloads are represented as single parameters (in Open API 2, `formData` could be composed of multiple parameters). Therefore there is no generic way to provide a more detailed level of access to the underlying data - it could be of any type allowed for JSON Schema, including primitive ones (e.g. `boolean`). The only parameter Schemathesis can give access to is the whole body.

> Have schemathesis read the example from this endpoint (provided in this open API definition)

Schemathesis tests explicit examples defined in the schema when invoked via CLI or pytest - what is your use case? Are existing ways to do so sufficient?

> case.body = schema['/pet']['post'].body[0].definition # application/json is the first one defined

Here you take the schema itself, but the `example` attribute will extract explicit examples from that parameter. Note that it is an internal API, and it could be changed in the future.

**Comment by Regala** [comment]
Hi folks thank you for the support. 

@Stranger6667 weird, I am using schemathesis.__version__ `3.7.3`:
![schema_ver](https://user-images.githubusercontent.com/1380527/120441598-a36b2080-c37c-11eb-856d-a742fd4d70e2.png)

Regarding the body, ok! Unfortunate as it will prevent my test case from working completely 😞  
What I'm doing is basically reading the schema and iterating over every single endpoint available; Then, manually invoking `.make_case` and passing it the required variables. To give you a clearer picture I'm basically doing something like this project: https://github.com/ngalongc/openapi_security_scanner - and I'm afraid we reached a similar stalemate, that is manipulating the body. 

Regarding the explict examples, how would I go about it to extract a full valid example body from them? Because inside e.g. ` schema['/pet']['post'].body[0].definition`, like you mentioned there is the `example` attribute on some so e.g. `schema['/pet']['post'].body[0].definition['schema']['properties']['name']['example']` ; but I guess there's no easy/straightforward way to come up with:
<img width="1401" alt="example" src="https://user-images.githubusercontent.com/1380527/120443559-acf58800-c37e-11eb-9652-86a62c0e15bf.png">
 
Thanks!

**Comment by Stranger6667** [comment]
It is strange. Here is my output with Schemathesis checked out to the `3.7.3` tag:

```
In [1]: import schemathesis

In [2]: schemathesis.__version__
Out[2]: '3.7.3'

In [3]: schema = schemathesis.from_uri("http://127.0.0.1:8081/schema.yaml", validate_schema=False)

In [4]: case = schema["/payload"]["post"].make_case(body={}, media_type="application/json")

In [5]: case.media_type
Out[5]: 'application/json'
```

Speaking of https://github.com/ngalongc/openapi_security_scanner - don't you have a local `schemathesis` directory like it is in that repo? In this case, the local directory will be preferred, and the installed version will be ignored, but it will still have the metadata gathered from the installed version (since it uses `importlib_metadata` internally). I believe it might be the cause of such behavior.

> I'm afraid we reached a similar stalemate, that is manipulating the body.

Could you elaborate on this, please? How would you see the usage of such a feature? We can think about it and maybe there is an appropriate solution for it.

> Regarding the explict examples, how would I go about it to extract a full valid example body from them? 

You could use `schema["/pet"]["post"].get_strategies_from_examples()` (which is a private API, though) - it will return a list of different strategies that will generate examples. For simplicity they could be combined:

```
strategies = schema["/pet"]["post"].get_strategies_from_examples()
example_strategy = strategies[0]
for strategy in strategies[1:]:
    example_strategy |= strategy
```

Then you can use it in a test function wrapped with `given`, or draw an example from it via the `.example()` method. However, there is a common warning on not using `given`:

> The `.example()` method is good for exploring strategies, but should only be used interactively.  We recommend using `@given` for tests - it performs better, saves and replays failures to avoid flakiness,  and reports minimal examples

But it depends on your workflow, I guess. Generally speaking, the initial purpose of `make_case` is to help to reproduce failures in stateful testing, and all the relevant bits there are private API. It might be better to design an API for this use case from scratch rather than repurpose the existing one.

**Comment by Regala** [comment]
Hey @Stranger6667 , thanks for the detailed feedback!

Regarding invoking `make_case` with the `media_type` you are totally right, the problem was using the local directory. 

> Could you elaborate on this, please? How would you see the usage of such a feature? We can think about it and maybe there is an appropriate solution for it.

Sure! I think it might be easier if I just describe the script I want to do in pseudo code.

So let's assume we continue to work with the https://petstore3.swagger.io/ API. First the main purpose of the script is to do an security assessment on access controls. So that means we will want to send one request with the session of one user A, and then do the same request with session of user B. If user A has access to the privileged resource `/api/pets/1/details` and then user B has also access to it, that would be considered a vulnerability. 

So the idea here is looping through all the available endpoints; retrieve the format of the request; doing the request with the necessary parameters and observe the request. The necessary parameters are supplied externally, in order to be sure we are hitting resources that exist. So in pseudo code and trying to combine what I know from schemathesis:

```
sessions = open('sessions.json')
variables = open('variables.json')
schema = schemathesis.from_path('pets.json')
 
for session in sessions:
  for endpoint in schema:
    for method in endpoint:
        case = schema[endpoint][method].make_case(path_parameters=variables, body=schema[current_endpoint][method].body)
        '''
        example if it was GET /pet/{petID} then inside variables we would need to have the petId variables
        if it was a POST body, e.g. POST /pet
            {
                "id": 10,
                "name": "doggie",
                "category": {
                    "id": 1,
                    "name": "Dogs"
                },
                "photoUrls": [
                    "string"
                ],
                "tags": [
                    {
                    "id": 0,
                    "name": "string"
                    }
                ],
                "status": "available"
             }

        then inside the variables.json file I would need to have the parameters id, name, category.id, category.name, etc
        '''
        response =  case.call()

        print method + " " + endpoint + " " + session.name + " : " response.status_code
```

Something like this! So as you see the biggest hurdle is with the body, because doing it with GET or DELETE it's trivial.

Thanks!!
