### ISSUE TITLE
[BUG] Authorization headers attribute is changed or removed by case.call()

### ISSUE THREAD

**Issue by DavidFarago** [schemathesis/schemathesis#1219]
**Describe the bug**
Authorization headers attribute set via `case.headers["Authorization"] = f'Bearer {AUTH_TOKEN}'` (see https://schemathesis.readthedocs.io/en/stable/recipes.html#authentication) is modified in `case.call()`. 

Printing `case` after setting it shows the correct `Authorization` attribute value, but authorization fails. 

Using
```
@schemathesis.hooks.register
def before_generate_case(context, strategy):
    def print_case(case):
        op = context.operation
        print(f'{op.method} {op.path} {case}')
        return case

    return strategy.map(print_case)
```
shows that the `Authorization` attribute is set to `Bearer 0` or `Bearer`.

Removing security settings in the OpenAPI json file, esp. 
```
"security": [
         {
           "bearerAuth": []
         }
       ]
```
results in the `Authorization` attribute being removed from the header by `case.call()`.

Thus I cannot authorize as described in https://schemathesis.readthedocs.io/en/stable/recipes.html#authentication.

**Expected behavior**
Correct authentication instead of `400`, `401` or `403` responses.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Python version: 3.7.6
 - Schemathesis version: 3.8.0
 - Spec version: 3.0.1 OpenAPI json

**Comment by DavidFarago** [comment]
Using the CLI via `schemathesis run -H "Authorization: Bearer HEREBETOKEN" --base-url=https://baseUrl swagger.json` does work correctly.

**Comment by Stranger6667** [comment]
Hm, from what I see, the header is sent to the app as intended:

```python
@schema.parametrize()
@settings(max_examples=5, deadline=2000)
def test_api(case):
    case.headers = case.headers or {}
    case.headers["Authorization"] = 'Bearer <removed>'
    print(f'Case before call(): {case}')
    response = case.call()
    print(response.request.headers)

@schemathesis.hooks.register
def before_generate_case(context, strategy):
    def print_case(case):
        op = context.operation
        print(f'{op.method} {op.path} {case}')
        return case

    return strategy.map(print_case)
```


When running this test with `pytest -rP main.py`, I see the following headers:

```
{'User-Agent': 'schemathesis/3.8.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'Bearer <removed>', 'Origin': '', 'Content-Type': 'application/json', 'Content-Length': '17'}
```

The `before_generate_case` hook is called just before the `case` variable gets to `test_api`.

That being said, I think that there might be some other condition that causes the authorization failure. Could you please check the `response.request.headers["Authorization"]` content?

**Comment by DavidFarago** [comment]
Thanks for your fast reply and pointing out that the request made is stored in the `response` object. You are right, the `Authorization` attribute is set correctly and authorization failure had a different cause (I believe CORS).
