### ISSUE TITLE
Is it possible to set a route's timeout with schemathesis.from_dict?

### ISSUE THREAD

**Issue by seano-vs** [schemathesis/schemathesis#1266]
**Is your feature request related to a problem? Please describe.**
Long story short, I'm trying to set an individual route's timeout in my schemathesis setup where I load an OAS3 config from dict. I've read the docs and looked through the source, but am still not sure if this is possible. Sorry if I am misinterpreting the docs, but I've had a few peers check my work and I am coming here as a last resort.

**Describe the solution you'd like**
Either a way to set an individual route's timeout, or [override the default timeout present in constants](https://github.com/schemathesis/schemathesis/blob/669755c7944ffef094d564001ec1ee4203a208aa/src/schemathesis/constants.py#L15).

Also, if it isn't too much trouble some documentation clarity around the different timeout values present (i.e. timeout vs. hypothesis deadline) would be extremely helpful if it isn't out of scope.

**Additional context**
This functionality may very well be present, and this is user error on my part.

**Comment by Stranger6667** [comment]
Hi @seano-vs !

Thank you for reporting it :)

I think you can do this by conditionally passing `timeout=N` to your `case.call` calls. E.g. 

```python
...

DEFAULT_TIMEOUT = 10  # or import from constants in schemathesis & divide by 1000

@schema.parametrize()
def test_api(case):
    timeout = {
        ("GET", "/users"): 5,
        # and so on
    }.get((case.operation.method.upper(), case.operation.path), DEFAULT_TIMEOUT)
    response = case.call(timeout=timeout)
    case.validate(response)
```

I hope that it solves the case :) And we can definitely improve the docs on this matter and how what are the roles of different similarly-named parameters (that hypothesis deadline vs timeout thing)

Cheers

**Comment by seano-vs** [comment]
Hey @Stranger6667!

Wow, this works great. I really appreciate the prompt response, this really got me up and running quickly! Thanks so much for your help!

**Comment by Stranger6667** [comment]
I am delighted to hear it, you are very welcome! :) 

I'll keep the issue open and will work on it once I have time

**Comment by Stranger6667** [comment]
Closing, as commits that update the docs (231f2a441a62952ae2ca6e6070222a681180f770 and b804378908d6550e3ab6a66a4bd080fe5cbb4c5c) are merged now
