### ISSUE TITLE
[FEATURE] В подсказке по воспроизведению проблемы показывать команду curl

### ISSUE THREAD

**Issue by ivanych** [schemathesis/schemathesis#1269]
Если какой-то тестируемый метод выдаёт ошибку, Схематезис выдаёт подказку со способом воспроизведения:

```
Run this Python code to reproduce this failure: 

    requests.get('http://site.ru/method/', headers={'User-Agent': 'schemathesis/3.10.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}, params={'title': '\x80'})
```

Было бы очень удобно, если бы помимо этого кода на Питоне выдавалась команда **curl**:

```
curl -v -X GET "http://site.ru/method/?title=\x80" -H  "User-Agent: schemathesis/3.10.0" ...
```
Так делает, к примеру, Сваггер. И это очень удобно — эту строчку можно отправить практически кому угодно и он её выполнит сходу, а вот код на Питоне выполнить не так-то просто, нужны дополнительные телодвижения.

**Comment by Stranger6667** [comment]
Существует отдельная [опция](https://schemathesis.readthedocs.io/en/stable/cli.html?highlight=Code-sample-style#code-samples-style ) чтобы изменить это поведение. Там curl как раз поддерживается. Я давно хотел сделать curl вариантом по-умолчанию, возможно пришло время :) 

Или все же имелось ввиду выводить оба варианта?

**Comment by ivanych** [comment]
А! Я извиняюсь, проморгал эту опцию.

Впрочем, думаю, действительно имеет смысл использовать по умолчанию именно curl - он универсальнее.
