### ISSUE TITLE
[FEATURE] Proxy traffic + disable certificate verification

### ISSUE THREAD

**Issue by wellenc-lex** [schemathesis/schemathesis#1274]
1: Add --proxy function to proxy traffic thru other tools.

2: add --no-verify function to allow self signed certificate to proxy https thru tools.

(Error example: Error: requests.exceptions.SSLError: HTTPSConnectionPool(host='', port=443): Max retries exceeded with url: /v0/docs/openapi.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

**Comment by ultras5631** [comment]
Found out that theres a cli parameter --request-tls-verify false , which is not obvious and really hard to find in DOCs. 
Would be nice to highlight it somehow.

Also the proxying could be done like that: http_proxy=http://localhost:8080 https_proxy=http://localhost:8080 schemathesis run

Hope it helps someone there.

**Comment by Stranger6667** [comment]
@ultras5631 

Thank you for opening this issue! I will update the docs on this matter and will keep this issue opened

**Comment by Stranger6667** [comment]
Closed via ec91777

**Comment by deft01** [comment]
Hi, how can I have the same behavior than `--request-tls-verify false` programmatically.

**Comment by deft01** [comment]
My script look like this :

```python
import schemathesis
from schemathesis import runner, models
from schemathesis.runner.events import *
import json

schema = schemathesis.from_path("swagger.json", base_url="https://SOMEONE-API/private/v1", validate_schema=True)

def write_to_file(response):
    with open("response.txt", "a") as f:
        f.write(str(repr(response)) + "\n")

def print_response(response):
        print(repr(response))
        print(dir(response))
        # some actions comming

def print_request(request):
    print(repr(request))
    print(dir(request))
    # some actions comming

@schema.parametrize
def test_api(case):
    case.call_and_validate(headers={"Authorization": f"Bearer some bearer"})

runner = schemathesis.runner.from_schema(schema)
for event in runner.execute():
    if isinstance(event, BeforeExecution):
        print_request(event)
    elif isinstance(event, AfterExecution):
        print_response(event)
```
I have two problems : 

1) I want to desactivate SSL check because I have `'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)\'` in the responses. I have tried `urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)` but not working.

2) I want to proxify my request programmatically. Not through the command line with `export http_proxy` or proxychains.
Is it possible ?

**Comment by deft01** [comment]
Im proxifying this script with `export http_proxy=http://127.0.0.1:8080 && export https_proxy=http://127.0.0.1` and get `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)`

**Comment by Stranger6667** [comment]
you can pass `verify=False` to `case.call_and_validate`

> Not through the command line with export http_proxy or proxychains. Is it possible ?

It should work out of the box, as Schemathesis uses `requests` under the hood which [supports](https://2.python-requests.org/en/master/user/advanced/#proxies) it:

```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```

**Comment by deft01** [comment]
I tried to modify the line containing call_and_validate as you mentionned :
`case.call_and_validate(headers={"Authorization": f"Bearer Test"}, verify=False)`
but it doesnt make it. I have still the same error.

For the proxy : yes it work with the environnement variables (export), but I would like to make it programmatically, directly in the python script. I havent seen anything that could let me pass my proxy configuration to schemathesis.

**Comment by deft01** [comment]
The stacktrace :
  ```File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 966, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.p
, line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/
thon3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wra
socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self
sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

During handling of the above ex
ption, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/
st-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError
pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'MY HOST\', port=443): Max retries exceeded with url: /services/financing/private/v1/api/rf
inquiry/sales/reply (Caused by SSLError(SSLCertVerificationError(1, \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)\')))

During ha
ling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/schemathesis/runner/impl/core.py", line 529, in network_
st
    response = _network_test(
  File "/home/user/.local/lib/python3.9/site-packages/schemathesis/runner/impl/core.py", line 587, in _network_test
    response = case.call(**kwargs)
  File "/home/user
local/lib/python3.9/site-packages/schemathesis/models.py", line 341, in call
    response = session.request(**data)  # type: ignore
  
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, request
    resp = self.send(prep, **send_kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-p
kages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host=\'MY HOST\', port=443): Max retries exceeded with u
: /services/financing/private/v1/api/rfq/inquiry/sales/reply (Caused by SSLError(SSLCertVerificationError(1, \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certific
e chain (_ssl.c:1123)\')))
', example=None, title=None)], interactions=[]), elapsed_time=0.09708010597387329, correlation_id='ab49bc3961fb42ab99ace2a34f3bb7d4', thread_id=139930439989056, hypothesis_output
```

**Comment by Stranger6667** [comment]
It should be possible to use the `proxies` argument:

```python
proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}

@schema.parametrize
def test_api(case):
    case.call_and_validate(headers={"Authorization": f"Bearer some bearer"}, proxies=proxies)
```

Schemathesis proxies almost everything you pass to `case.call_and_validate` to `requests.Session.request`, including `verify` & `proxies`, so there should be no difference with using `requests` directly with those arguments.

**Comment by Stranger6667** [comment]
Does it work with plain `requests`?

**Comment by deft01** [comment]
Yes with plain `requests` it works.
I founded an option (not documented i believe) that can desactivate the SSL checks.
`runner.request_tls_verify = False`

And it works like this !

**Comment by deft01** [comment]
I will investigate if I have the time, why the options passed to the `requests` module through the **kwargs are not working.

**Comment by Stranger6667** [comment]
Oh, I didn't notice this block:

```
runner = schemathesis.runner.from_schema(schema)
for event in runner.execute():
    if isinstance(event, BeforeExecution):
        print_request(event)
    elif isinstance(event, AfterExecution):
        print_response(event)
```

and was thinking only about `@schema.parametrize`. Sorry!

So, you could pass `request_tls_verify` to `from_schema`. These options are not passed to `requests` - for this, you need to use the [process_call_kwargs](https://schemathesis.readthedocs.io/en/stable/extending.html?highlight=process_call_kwargs#process-call-kwargs) hook

**Comment by deft01** [comment]
Okay ! I understand now.

I came with this piece of code :
```python
(...)

proxies = {
  'http': 'http://127.0.0.1:8080',
  'https': 'http://127.0.0.1:8080'
}

@schemathesis.hooks.register
def process_call_kwargs(context, case, kwargs):
    kwargs["session"].headers.update({"Authorization": "Bearer token"})
    kwargs["session"].proxies = proxies

runner = schemathesis.runner.from_schema(schema)
runner.request_tls_verify = False
for event in runner.execute():
    if isinstance(event, BeforeExecution):
        print("BeforeExecution")
    elif isinstance(event, AfterExecution):
        print("AfterExecution")
```

It is proxying programmatically + removing the check on SSL.
Thank you a lot for your help :+1:

**Comment by Stranger6667** [comment]
You're very welcome! :)
