### ISSUE TITLE
[BUG] oneOf doesn't work as expected

### ISSUE THREAD

**Issue by doraeric** [schemathesis/schemathesis#1297]
**Describe the bug**
Using `oneOf` in response content schema doesn't work as expected, it failed while it should pass

**To Reproduce**
1. save the yaml below
2. run `schemathesis run --base-url https://ipinfo.io --checks all ./example.yml` and see failed

If possible, please post a minimal version of your API schema that cause this behavior:

```yaml
openapi: "3.0.3"
info:
  title: Test API
  version: "1"
servers:
  - url: https://ipinfo.io
paths:
  /8.8.8.8/json:
    get:
      description: IP
      responses:
        "200":
          description: OK
          content:
            application/json; charset=utf-8:
              schema:
                oneOf:
                  - type: object
                    properties:
                      error:
                        type: string
                  - type: object
                    properties:
                      ip:
                        type: string
                      hostname:
                        type: string
                      anycast:
                        type: boolean
                      city:
                        type: string
                      region:
                        type: string
                      country:
                        type: string
                      loc:
                        type: string
                      org:
                        type: string
                      postal:
                        type: string
                      timezone:
                        type: string
                      readme:
                        type: string
```

**Expected behavior**
Pass response_schema_conformance check

**Environment (please complete the following information):**
 - OS: linux
 - Python version: 3.9.7
 - Schemathesis version: 3.10.1
 - Spec version: Open API 3.0.3

**Comment by doraeric** [comment]
Thank you for the explanation!
I am learning OpenAPI and the explanation helps me understand better.
The suggestion did what I want, thank you!

**Comment by Stranger6667** [comment]
@doraeric you're very welcome :) Let me know if I can provide more info

Added a new FAQ entry to the docs, so closing this. The error message improvements are tracked separately
