### ISSUE TITLE
[REQUEST FOR DOCUMENTATION] docker with local spec

### ISSUE THREAD

**Issue by braco** [schemathesis/schemathesis#1299]
It's nice to run docker instead of dealing with pip on different machines.

However, it's not clear how to get a local schema file into docker.

```
docker run schemathesis/schemathesis:stable run build/spec.yml -b https://api.com -H "X-API-Key: ..."
```

This would yield `Error: Invalid SCHEMA, must be a valid URL or file path.`, which makes sense. 

Think the answer is to mount:

`docker run -v $PWD/build:/mnt/build schemathesis/schemathesis:stable run /mnt/build/spec.yml -b https://api.com -H "X-API-Key: ..."`

Related:
- https://github.com/schemathesis/schemathesis/issues/1288

**Comment by Stranger6667** [comment]
Done via c55fde2
