### ISSUE TITLE
[FEATURE] Examples in nested objects

### ISSUE THREAD

**Issue by hoog1511** [schemathesis/schemathesis#1320]
**Is your feature request related to a problem? Please describe.**
I am working with an application which allows a user to post a object which has nested objects/arrays as parameters. When I run Schemathesis tests using the OpenAPI schema I setup for the application the first testcase shown in the debug outputfile does not contain said object/array and their parameters in the body of the request. 
```json
"Body            : {'param1': '12345'}
```

**Describe the solution you'd like**
I would like to be able to run Schemathesis tests using nested objects without having to provide an example for the entire object. See schema for more clarification:
```yaml
requestObject:
      title: requestObject
      required: 
        - nestedArray
        - nestedObject
      type: object
      properties:
        param1:
          maxLength: 5
          type: string
        array:
          type: array
          minItems: 1
          #example:
              #-nestedArrayObjectParam1: foo
              #  nestedArrayObjectParam2: bar
          items:
            $ref: "#/components/schemas/nestedArrayObject"
        external_object:
          $ref: "#/components/schemas/nestedObject"
      additionalProperties: false
```
```json
"Body            : {'param1': '12345', 'array': [{'nestedArrayObjectParam1': 'foo', 'nestedArrayObjectParam2': 'bar'}], 'nestedObject': {'param1: 'foo'}}
```

**Describe alternatives you've considered**
The only workaround I have found for this issue is providing a example for the entire object/array.

**Comment by Stranger6667** [comment]
Thanks for reporting! 
Indeed, it is a limitation I'd be happy to lift off - I was planning to revise the example generation code, so it would be definitely within the revision scope.
