### ISSUE TITLE
[FEATURE] Upgrade click to version 8

### ISSUE THREAD

**Issue by quaterneon** [schemathesis/schemathesis#1328]
**Is your feature request related to a problem? Please describe.**
I have a dependency management issue due to the outdated version of click used by this library.

**Describe the solution you'd like**
 Please update pinned version of click to `^8.0.0`. A significant number of changes were made with this version: https://click.palletsprojects.com/en/8.0.x/changes/

**Describe alternatives you've considered**

**Additional context**

**Comment by Stranger6667** [comment]
Thanks for reporting & implementing it! Much appreciated

Resolved via #1329

**Comment by Stranger6667** [comment]
Released in `3.11.1`
