### ISSUE TITLE
[FEATURE] prevent empty input in testcases

### ISSUE THREAD

**Issue by hoog1511** [schemathesis/schemathesis#1349]
**Is your feature request related to a problem? Please describe.**
Not to my knowledge

**Describe the solution you'd like**
I would like to be able to prevent empty input in testcases when I add minlength, minimum or required to a parameter within a schema. In my experience most of my testcases tend to have empty values given to the parameters that have these properties/field.

**Describe alternatives you've considered**
I have added patterns to try and prevent empty input, but this does not always work.

**Additional context**
![image](https://user-images.githubusercontent.com/22965220/145024799-5ae3ba89-fc31-471e-8b03-de38012f0bc6.png)

**Comment by Stranger6667** [comment]
Hi!

Thanks for reporting! By empty values, do you mean strings composed entirely from whitespace or strings with size 0? #801 might be related to this, but it highly depends on schema complexity.

If the matter is about strings containing only whitespace, then the shrinking process might be in the play. Hypothesis minimizes the examples, and it tends to minimize strings to simple values like whitespace. Could it be the case? Or Schemathesis generates these kinds of values during the whole testing process?

> I have added patterns to try and prevent empty input, but this does not always work.

That is quite unfortunate, but when the `pattern` keyword is involved, the underlying library [uses rejection sampling](https://github.com/Zac-HD/hypothesis-jsonschema/blob/master/src/hypothesis_jsonschema/_from_schema.py#L443) which might negatively affect the quality of the generated data. It might be better, for now, to include the size bounds into the pattern itself (in the example above the `minLength` could be removed, as the pattern implies min size of 1)

**Comment by hoog1511** [comment]
#801 does seem to be related to my issue. To clarify, I want no whitespace for my values because the application I am testing is quite strict with the values required to get happy flow (200, 201, etc.) responses. I think due to the nesting of objects in the application, schemathesis somehow can't find the configurations I have given for parameters (required, minLength, patterns, etc.) and tends to just use whitespace instead. Most of my test results tend to have one or two happy flow results and all the others 400.

**Comment by Stranger6667** [comment]
@hoog1511 

Sorry for not getting back to you earlier. If Schemathesis generates only whitespace for the schema above, then it is definitely a bug. If whitespace is happening only at the end of generated strings, then it is likely should be fixed by #1361 (released in 3.12). Let me know the new release fixes the issue, otherwise, could you please, share your API schema (partial/anonymized is OK)?
