### ISSUE TITLE
[FEATURE] Update typing-extensions requirement to allow >4

### ISSUE THREAD

**Issue by vikahl** [schemathesis/schemathesis#1362]
**Is your feature request related to a problem? Please describe.**

I get dependency problems when installing `schemathesis==3.11.7` together with my other dependencies.

```
The conflict is caused by:
    The user requested typing-extensions==4.0.1
    libcst 0.3.23 depends on typing-extensions>=3.7.4.2
    pydantic[email] 1.8.2 depends on typing-extensions>=3.7.4.3
    typing-inspect 0.7.1 depends on typing-extensions>=3.7.4
    pylint 2.12.2 depends on typing-extensions>=3.10.0; python_version < "3.10"
    black 21.12b0 depends on typing-extensions>=3.10.0.0
    schemathesis 3.11.7 depends on typing-extensions<4.0 and >=3.7
```

**Describe the solution you'd like**

Loosen`typing-extension` requirement to allow `>4.0`.  I don't have enough context to know if just creating a PR will be enough.

**Comment by Stranger6667** [comment]
Hi! Thanks for reporting :)

Yeah, I think that creating a PR that changes the dependency should be enough

**Comment by Stranger6667** [comment]
Let me know if you'd like to submit a PR :) If not, I'll add it during this week

**Comment by vikahl** [comment]
Thanks, I'll create a PR today.
