### ISSUE TITLE
Malformed Type "text" in hyptohesis schemathesis run 

### ISSUE THREAD

**Issue by RifaaD** [schemathesis/schemathesis#1382]
**Issue:** Malformed media type "text" in content_type_conformance checks 

1. Malformed media type: `text <Deleted information due to security>

Issue comes back as 401 error and is replicated after every run with 401 text/html response in schemathesis oas file.
Any idea on potential fixes for this issue and expected base problem?

**Comment by Stranger6667** [comment]
Hi @RifaaD 

Could you, please, share your API schema? Generally speaking, media types in Open API should follow [RFC 6838](https://datatracker.ietf.org/doc/html/rfc6838) where "text" does not (it is only `type-name` & missing `subtype-name`), hence the issue. A valid media type would be "text/plain" or "text/html".
Note that the check refers to what is declared in the schema, not to the "Content-Type" response header.

**Comment by Stranger6667** [comment]
I adjusted the error message in #1446, which should make the underlying issue a bit more clear. It will be released in the next version. Feel free to reopen this issue if you'll find those changes not sufficient.
