### ISSUE TITLE
[FEATURE] Print seed in header printed at `schemathesis run`

### ISSUE THREAD

**Issue by niya3** [schemathesis/schemathesis#1384]
**Is your feature request related to a problem? Please describe.**
I wan't to know the generated `seed` value even when `schemathesis run` ended without errors **or** checks weren't started **or** if checks were interrupted (in case the `schemathesis run` or my server or both are hanging). It could be interesting to reproduce run with this seed and try to detect the root of the issue.

**Describe the solution you'd like**
I think it would be cool to add seed in header printed at `schemathesis run` start.

**Describe alternatives you've considered**
Now i can get seed from VCR cassete, if it was collected during run.

**Additional context**
my current header:
```
platform Linux -- Python 3.10.1, schemathesis-3.12.3, hypothesis-6.32.1, hypothesis_jsonschema-0.22.0, jsonschema-4.3.2
rootdir: $MY_DIR
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/$MY_DIR/.hypothesis/examples')
Schema location: $MY_SCHEMA_FILE
Base URL: $MY_URL
Specification version: Open API 3.0.0
Workers: 1
Collected API operations: 1
```

**Comment by Stranger6667** [comment]
Good point! Will add it

**Comment by Stranger6667** [comment]
Oh, it is a bit more complicated than I thought - the used seed is per-endpoint, but it depends on hypothesis configuration. Not sure what to do about it yet

**Comment by Stranger6667** [comment]
I think I'd rather set seed globally for all tests - there is no actual difference in effectiveness, but the overall UX is simpler.
