### ISSUE TITLE
[BUG] 5xx status code

### ISSUE THREAD

**Issue by hoog1511** [schemathesis/schemathesis#1393]
**Describe the bug**
I'm currently trying to perform schemathesis tests against an application of mine and it keeps returning the error:
"Received a response with 5xx status code: 500"

I have a 500 response defined in my schema, but this error does not seem to say that there is an issue within the schema itself.

Is there a way to turn off this particular check? The current solution I am using is adding "--hypothesis-phases=explicit" to the CLI command, but this will prevent any checks for uncommon testcases.

**Environment (please complete the following information):**
 - Windows
 - Pega
 - Schemathesis version: latest
 - Spec version: 3.0.1

**Comment by Stranger6667** [comment]
Hi @hoog1511 

Thanks for reporting :) The failure comes from the "not_a_server_error" check which is enabled by default and fails on any 5xx response.

> Is there a way to turn off this particular check?

There is no way to disable a particular check at the moment - you might want to explicitly submit only needed checks via the "-c" command-line option:

```
schemathesis run ... -c status_code_conformance -c content_type_conformance -c response_headers_conformance -c response_schema_conformance
```

There was #923 on this matter, but I thought it might be a bit confusing when `-c` is combined with its exclusion counterpart. Also, #1373 might help a bit here.

What do you think? Would the above solution work for your case?

**Comment by hoog1511** [comment]
I have tried adding the `-c status_code_conformance -c content_type_conformance -c response_headers_conformance -c response_schema_conformance` to my test, but it still runs the server_error check which causes my issue. The root cause of my issue is that one of the testcases performed against my API adds a value which does not conform with my provided regex `"[\d]{8}"` values like `0000000𐒠` will be added for instance.

**Comment by Stranger6667** [comment]
> I have tried adding the -c status_code_conformance -c content_type_conformance -c response_headers_conformance -c response_schema_conformance to my test, but it still runs the server_error check which causes my issue

It does look like a bug to me, but I can not reproduce it. I tried it with the built-in server with the following command:

```
./test_server.sh 8081  --spec=openapi3 --operations=failure
```

It has a single endpoint that fails all the time which should trigger the `not_a_server_error` check. Then I have the following output from Schemathesis:

```
stranger6667@archlinux:/tmp|⇒  schemathesis run http://127.0.0.1:8081/schema.yaml -c status_code_conformance -c content_type_conformance -c response_headers_conformance -c response_schema_conformance
=========================================== Schemathesis test session starts ===========================================
platform Linux -- Python 3.10.2, schemathesis-3.11.6, hypothesis-6.32.1, hypothesis_jsonschema-0.22.0, jsonschema-4.3.2
rootdir: /tmp
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/tmp/.hypothesis/examples')
Schema location: http://127.0.0.1:8081/schema.yaml
Base URL: http://127.0.0.1:8081/api
Specification version: Open API 3.0.2
Workers: 1
Collected API operations: 1

GET /api/failure F                                                                                                [100%]

======================================================= FAILURES =======================================================
_________________________________________________ GET /api/failure [P] _________________________________________________
1. Received a response with 'text/plain; charset=utf-8' Content-Type, but it is not declared in the schema.

Defined content types: application/json

Headers         : {'User-Agent': 'schemathesis/3.11.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}

----------

Response payload: `500: Internal Server Error`

Run this cURL command to reproduce this failure: 

    curl -X GET -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'User-Agent: schemathesis/3.11.6' http://127.0.0.1:8081/api/failure

Or add this option to your command line parameters: --hypothesis-seed=185187995504599918471795127729041536953
======================================================= SUMMARY ========================================================

Performed checks:
    status_code_conformance                         2 / 2 passed          PASSED 
    content_type_conformance                        0 / 2 passed          FAILED 
    response_headers_conformance                    2 / 2 passed          PASSED 
    response_schema_conformance                     2 / 2 passed          PASSED 

================================================== 1 failed in 0.04s ===================================================
```

So it triggers `content_type_conformance` to fail and as far as I can tell `not_a_server_error` is not executed. How did you run Schemathesis? Maybe there is some input combination/situation where the check is not properly disabled, but at this moment I am not sure where such a thing might happen.

> adds a value which does not conform with my provided regex "[\d]{8}" values like 0000000𐒠 will be added for instance.

It indeed does not conform with ECMAScript regex behavior. In Python (and in C# for example) `\d` covers not only 0-9 digits but also all Unicode numeric values, therefore `𐒠` (`\U000104a0` / [OSMANYA DIGIT ZERO](https://www.fileformat.info/info/unicode/char/104a0/index.htm)) matches the regex. As a workaround, you might want to replace `\d` with `[0-9]` to cover only ASCII digits instead.

However, as we aim to cover ECMAScript compliant behavior, we might consider changing this aspect. Not sure if using `re.ASCII` would help internally - need to check how Python's regex behavior intersects with ECMAScript one in other aspects.

**Comment by hoog1511** [comment]
The command I used to perform the schemathesis test is: `schemathesis run oas.yaml -c all --base-url https://server.com --show-errors-tracebacks -store-network-log=traceback.yml --debug-output-file=output.yml --hypothesis-deadline=none --request-tls-verify=false --hypothesis-supress-health-check=too_slow --H apiKey:"....."` followed by some other headers.
