### ISSUE TITLE
[BUG] Depends on deprecated class removed from Werkzeug

### ISSUE THREAD

**Issue by DanLipsitt** [schemathesis/schemathesis#1410]
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
Schemathesis will not run because deprecated module `werkzeug.wrappers.json` has been [removed](https://github.com/pallets/werkzeug/pull/2276/files#diff-130d7504b20901f2f461333aacfeaaf0063ca036f03dcd2e850eb1b86163e6da) in [Werkzeug version 2.1.0](https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0).

**To Reproduce**

In a fresh virtualenv, `pip install schemathesis`. Then run the following in the python shell:

```python
>>> import werkzeug
>>> werkzeug.__version__
'2.1.0'
>>> import schemathesis
Traceback (most recent call last):
  Input In [4] in <cell line: 1>
    import schemathesis
  File ~/.local/share/virtualenvs/b743d625b5a38ba/lib/python3.10/site-packages/schemathesis/__init__.py:7 in <module>
    from . import fixups, hooks, runner, serializers, targets
  File ~/.local/share/virtualenvs/b743d625b5a38ba/lib/python3.10/site-packages/schemathesis/fixups/__init__.py:3 in <module>
    from . import fast_api
  File ~/.local/share/virtualenvs/b743d625b5a38ba/lib/python3.10/site-packages/schemathesis/fixups/fast_api.py:3 in <module>
    from ..hooks import HookContext, register, unregister
  File ~/.local/share/virtualenvs/b743d625b5a38ba/lib/python3.10/site-packages/schemathesis/hooks.py:11 in <module>
    from .utils import GenericResponse, deprecated_property
  File ~/.local/share/virtualenvs/b743d625b5a38ba/lib/python3.10/site-packages/schemathesis/utils.py:40 in <module>
    from werkzeug.wrappers.json import JSONMixin
ModuleNotFoundError: No module named 'werkzeug.wrappers.json'
````

**Expected behavior**
Schemathesis should load.

**Environment (please complete the following information):**
 - OS: MacOS 12.2
 - Python version: 3.10.2
 - Schemathesis version: 3.13.3
 - Spec version: n/a

**Comment by Stranger6667** [comment]
Thanks for reporting! I will have a look

**Comment by DanLipsitt** [comment]
Thanks! Werkzeug changelog says `Request and response mixins have all been merged into the Request and Response classes` but I don't know exactly how.

**Comment by Bidaya0** [comment]
> Thanks for reporting! I will have a look

Shouldn't there be an hotfix release here to fix it?
I looked at the pyproject.toml for the record and this may have affected quite a few released distributions.

**Comment by Stranger6667** [comment]
If the mixin was merged, then it would be nice to have conditional logic, that uses `JSONMixin` if it is available and creates an empty mixin if it is not. This way we should be able to support all werkzeug versions

**Comment by Stranger6667** [comment]
Resolved in `3.13.4`. Thank you everybody involved

https://pypi.org/project/schemathesis/3.13.4/

**Comment by Stranger6667** [comment]
Hi @mm-gmbd 

I'll take a look at it

**Comment by Stranger6667** [comment]
@mm-gmbd 

`2.8.6` is released with the fix - https://pypi.org/project/schemathesis/2.8.6/

**Comment by mm-gmbd** [comment]
Thanks, kind @Stranger6667!
