### ISSUE TITLE
Revise dependency constraints

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#1417]
I'd like to revise the current dependencies constraints to avoid situations like #1410. We need a safer approach & avoid unconstrained dependencies

**Comment by Bidaya0** [comment]
These are some of my experiences in project management.
1. Confirm the release policy of the dependency.
2. Take xx as an example, as I commented in [https://github.com/schemathesis/schemathesis/pull/1411](https://github.com/schemathesis/schemathesis/pull/1411) . At least by keeping them in MINOR version of [semantic versioning](https://semver.org/) to keep backwards compatible. And carefully update the adaptation after the release of the MAJOR version of the dependency.
3. If the dependencies are not released in accordance with the semantic versioning, refer to the method in 2. to control the version to the range that ensures backward compatibility, and release the update and expand the corresponding dependency range after incompatible dependency version appears.

**Comment by Stranger6667** [comment]
Thanks!

Closing this as I capped the versions of all dependencies
