### ISSUE TITLE
[DOCS] Unstable link anchors in changelog

### ISSUE THREAD

**Issue by Zac-HD** [schemathesis/schemathesis#1474]
I recently wanted to send someone a link to the changelog entry for a particular version.

Unfortunately, without ref anchors in the `rst` file, the generated HTML uses sequential link anchors, and with each new release `#id3` will be further and further from what I'd intended.  See https://github.com/HypothesisWorks/hypothesis/commit/fe4ac8479ce9be356fdaa704f892963c1245ce5e for an example fix.

**Comment by Stranger6667** [comment]
Thanks! Fixed :) The new release will contain stable anchors
