### ISSUE TITLE
[BUG] OpenAPI links with runtime expression in requestBody are not evaluated

### ISSUE THREAD

**Issue by azeeka** [schemathesis/schemathesis#1573]
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
Runtime expression in `requestBody` section of the link is not evaluated

**To Reproduce**
1. Command to run the test:
```bash
st run openapi.yaml --base-url=http://localhost:8000/api/v1/ --checks all --show-errors-tracebacks --hypothesis-max-examples 1
```
2. Output of the test:
```bash
======================================== SUMMARY =========================================

Performed checks:
    not_a_server_error                              4 / 4 passed          PASSED 
    status_code_conformance                         4 / 4 passed          PASSED 
    content_type_conformance                        4 / 4 passed          PASSED 
    response_headers_conformance                    4 / 4 passed          PASSED 
    response_schema_conformance                     4 / 4 passed          PASSED 

Hint: You can visualize test results in Schemathesis.io by using `--report` in your CLI command.
```

<details>
  <summary>3. API Schema:</summary>

```yaml
openapi: 3.0.0
info:
  title: Basic
  version: 1.0.0
  description: Basic API Schema
servers:
  - url: "http://localhost:8000/api/v1"
    description: Development
paths:
  /auth/token/:
    post:
      summary: ""
      operationId: token_create
      description: Retrieve JWT Tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Credentials"
            examples:
              testuser1:
                value:
                  username: tony
                  password: WarMachine68
        description: Credentials for log in
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenPair"
              examples:
                jwt-1:
                  value:
                    access: eySuperdupersecureaccesstoken777
                    refresh: eyWeareAlwaysFreshArentwe666
          links:
            GetRefreshedTokens:
              operationId: token_refresh_create
              requestBody:
                refresh: $response.body#/refresh
        "400":
          description: Bad Request
        "401":
          $ref: "#/components/responses/StatusWithDetails"
      tags:
        - token
      security: []
  /auth/token/refresh/:
    post:
      summary: ""
      operationId: token_refresh_create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshRequestBody"
        description: Refresh token
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenPair"
              examples:
                jwt-1:
                  value:
                    access: eyTryAccessingwithme123
                    refresh: eyFreshtokensAginglikeafinewine
        "400":
          description: Bad Request
        "401":
          $ref: "#/components/responses/StatusWithDetails"
      tags:
        - token
      security: []
components:
  schemas:
    TokenPair:
      title: TokenPair
      type: object
      properties:
        refresh:
          type: string
        access:
          type: string
      required:
        - refresh
        - access
    Credentials:
      title: Credentials
      type: object
      properties:
        username:
          type: string
          example: rhodey
        password:
          type: string
          example: openupgulchetai
      required:
        - username
        - password
    RefreshRequestBody:
      title: RefreshRequestBody
      type: object
      properties:
        refresh:
          type: string
      required:
        - refresh
    StatusWithDetails:
      title: StatusWithDetails
      type: object
      properties:
        details:
          type: string
  securitySchemes:
    JWT:
      name: Bearer
      type: apiKey
      in: header
      description: ""
  responses:
    StatusWithDetails:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StatusWithDetails"
          examples:
            Invalid token:
              value:
                details: token is invalid
security:
  - JWT: []
tags:
  - name: token
```
</details>

<details>
  <summary>4. Request logs on the server (look at the last requests):</summary>

`> request POST /api/v1/auth/token/`
**headers:** {'Content-Length': '44', 'Content-Type': 'application/json', 'Host': 'localhost:8000', 'User-Agent': 'schemathesis/3.16.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Schemathesis-Testcaseid': '0b0fc40965464142a324728645fd8bad'}
**body:** '{"username": "tony", "password": "WarMachine68"}'

`< response POST /api/v1/auth/token/ - 200`
**headers:** {'Content-Type': 'application/json', 'Vary': 'Accept', 'Allow': 'POST, OPTIONS'}
**body:** '{"refresh":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY1OTE4ODE3OCwiaWF0IjoxNjU5MTAxNzc4LCJqdGkiOiI3M2FkYTIwNmI0YTg0MmU4YTFjMzU3NGQ3NTMwM2JmNCIsInVzZXJfaWQiOjF9.iLVJlY--J2aT8EtsEc-lF3T9wMOe128Pr3-IB4Kg7Ns","access":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5MTAyMDc4LCJpYXQiOjE2NTkxMDE3NzgsImp0aSI6ImQxYzRlMDQyZmM4MjRkMmU5ZmU3ZGQzZmMwZDU2YzIzIiwidXNlcl9pZCI6MX0.-4XrLzuuZCvgL_6WPJ2l79hti-wEClZbWoUqdy0Imjk"}'
`[29/Jul/2022 13:36:18] "POST /api/v1/auth/token/ HTTP/1.1" 200 483`

`> request POST /api/v1/auth/token/`
**headers:** {'Content-Length': '44', 'Content-Type': 'application/json', 'Host': 'localhost:8000', 'User-Agent': 'schemathesis/3.16.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Schemathesis-Testcaseid': 'caf87737ce8a4660be0470a31092605a'}
**body:** '{"username": "rhodey", "password": "openupgulchetai"}'

`< response POST /api/v1/auth/token/ - 200`
**headers:** {'Content-Type': 'application/json', 'Vary': 'Accept', 'Allow': 'POST, OPTIONS'}
**body:** '{"refresh":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY1OTE4ODE3OCwiaWF0IjoxNjU5MTAxNzc4LCJqdGkiOiI0MGNjNzgzZjRmZGM0MmQ4ODk0MTJmMjg4ODY3NTM4ZiIsInVzZXJfaWQiOjF9.X1mWZgnoBpsXD1yw1yfI8zWyldWK7hDp21C5BidwxyQ","access":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5MTAyMDc4LCJpYXQiOjE2NTkxMDE3NzgsImp0aSI6ImIxMDY1ODEzMTJkOTQ3ZDJhOTU1MzYzMDFlOTExZDViIiwidXNlcl9pZCI6MX0.Fh9Zo9IDxlpNprX7iWXZFoR23rqx_sCyrrG6C2t9h9U"}'
`[29/Jul/2022 13:36:18] "POST /api/v1/auth/token/ HTTP/1.1" 200 483`

`> request POST /api/v1/auth/token/`
**headers:** {'Content-Length': '89', 'Content-Type': 'application/json', 'Host': 'localhost:8000', 'User-Agent': 'schemathesis/3.16.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Schemathesis-Testcaseid': 'cad9ade922034d29a5df374c6c3cd811'}
**body:** '{"password": "", "username": "", "": [{"": null}, [-16842888.0, [136201856], false], []]}'

`< response POST /api/v1/auth/token/ - 400`
**headers:** {'Content-Type': 'application/json', 'Vary': 'Accept', 'Allow': 'POST, OPTIONS'}
**body:** '{"username":["This field may not be blank."],"password":["This field may not be blank."]}'
Bad Request: /api/v1/auth/token/
`[29/Jul/2022 13:36:18] "POST /api/v1/auth/token/ HTTP/1.1" 400 89`

`> request POST /api/v1/auth/token/refresh/`
**headers:** {'Content-Length': '38', 'Content-Type': 'application/json', 'Host': 'localhost:8000', 'User-Agent': 'schemathesis/3.16.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Schemathesis-Testcaseid': '013c7fe2af2a48ba9dd9ffa6e0b0034f'}
**body:** '{"refresh": "$response.body#/refresh"}'

`< response POST /api/v1/auth/token/refresh/ - 401`
**headers:** {'Content-Type': 'application/json', 'WWW-Authenticate': 'Bearer realm="api"', 'Vary': 'Accept', 'Allow': 'POST, OPTIONS'}
**body:** '{"detail":"Token is invalid or expired","code":"token_not_valid"}'
Unauthorized: /api/v1/auth/token/refresh/
`[29/Jul/2022 13:36:18] "POST /api/v1/auth/token/refresh/ HTTP/1.1" 401 65`

`> request POST /api/v1/auth/token/`
**headers:** {'Content-Length': '44', 'Content-Type': 'application/json', 'Host': 'localhost:8000', 'User-Agent': 'schemathesis/3.16.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Schemathesis-Testcaseid': 'a3eaf4338de54119a2293782783d8eb5'}
**body:** '{"username": "tony", "password": "WarMachine68"}'

`< response POST /api/v1/auth/token/ - 200`
**headers:** {'Content-Type': 'application/json', 'Vary': 'Accept', 'Allow': 'POST, OPTIONS'}
**body:** '{"refresh":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY1OTE4ODQzMiwiaWF0IjoxNjU5MTAyMDMyLCJqdGkiOiI4ZWEyZDY5NzIyNDA0MGRhOGY3M2MyY2MzMzhmNWNjMyIsInVzZXJfaWQiOjF9.-q6xxDwAfPswCGWC96P7LRZquskq9RURMjz9fCS-J_A","access":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5MTAyMzMyLCJpYXQiOjE2NTkxMDIwMzIsImp0aSI6Ijc1NzMxYzk0ZDc1YjQ3MjBiZDA3ZWUxYjJlNmZhMDNiIiwidXNlcl9pZCI6MX0.B9elyYvcy7yMNvwAGRgL4DJ5_5D2V7X46LZg5-eXyIw"}'
`[29/Jul/2022 13:40:32] "POST /api/v1/auth/token/ HTTP/1.1" 200 483`

`> request POST /api/v1/auth/token/`
**headers:** {'Content-Length': '44', 'Content-Type': 'application/json', 'Host': 'localhost:8000', 'User-Agent': 'schemathesis/3.16.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Schemathesis-Testcaseid': '1e8b7b8963dd47caa5b1ed5cb7af8188'}
**body:** '{"username": "rhodey", "password": "openupgulchetai"}'

`< response POST /api/v1/auth/token/ - 200`
**headers:** {'Content-Type': 'application/json', 'Vary': 'Accept', 'Allow': 'POST, OPTIONS'}
**body:** '{"refresh":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY1OTE4ODQzMiwiaWF0IjoxNjU5MTAyMDMyLCJqdGkiOiJlZDAyY2JkYmVhNzc0MWM4YjM4YTNkM2FmMWE0MjllMyIsInVzZXJfaWQiOjF9.KyRhGbPG3KQq3Vw8-D8lNMwbq8NbHb8IHp1cPxw1CwU","access":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5MTAyMzMyLCJpYXQiOjE2NTkxMDIwMzIsImp0aSI6IjRhNjQwOGNhNjcyNzRjNThiNDVlZmZlNGZmYjkxNWRiIiwidXNlcl9pZCI6MX0.D9HOlaO4adI-Ye0p8xEphhc9CYDkmlJF_FC0zAysU68"}'
`[29/Jul/2022 13:40:32] "POST /api/v1/auth/token/ HTTP/1.1" 200 483`

`> request POST /api/v1/auth/token/`
**headers:** {'Content-Length': '72', 'Content-Type': 'application/json', 'Host': 'localhost:8000', 'User-Agent': 'schemathesis/3.16.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Schemathesis-Testcaseid': 'd265a0c9427b4ecfb98403d6be97d43f'}
**body:** '{"password": "", "username": "", "": [{"": null}, [-16842888.0, [-70]]]}'

`< response POST /api/v1/auth/token/ - 400`
**headers:** {'Content-Type': 'application/json', 'Vary': 'Accept', 'Allow': 'POST, OPTIONS'}
**body:** '{"username":["This field may not be blank."],"password":["This field may not be blank."]}'
Bad Request: /api/v1/auth/token/
`[29/Jul/2022 13:40:32] "POST /api/v1/auth/token/ HTTP/1.1" 400 89`

`> request POST /api/v1/auth/token/refresh/`
**headers:** {'Content-Length': '38', 'Content-Type': 'application/json', 'Host': 'localhost:8000', 'User-Agent': 'schemathesis/3.16.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'X-Schemathesis-Testcaseid': 'ac58f1c7bbd0491ab79e9b82cedebc31'}
**body:** **'{"refresh": "$response.body#/refresh"}'** 
             **^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^**

`< response POST /api/v1/auth/token/refresh/ - 401`
{'Content-Type': 'application/json', 'WWW-Authenticate': 'Bearer realm="api"', 'Vary': 'Accept', 'Allow': 'POST, OPTIONS'}
**body:** '{"detail":"Token is invalid or expired","code":"token_not_valid"}'
Unauthorized: /api/v1/auth/token/refresh/
`[29/Jul/2022 13:40:32] "POST /api/v1/auth/token/refresh/ HTTP/1.1" 401 65`

</details>

-----

**Expected behavior**
`refresh` field of the request body should be substituted with the runtime expression value, like `{"refresh": "eyJ0eXAiOiJ...."}`

**Environment:**
 - OS: macOS 11.6
 - Python version: 3.9.6
 - Schemathesis version: 3.16.0
 - Spec version: Open API 3.0.0

**Additional context**
 - Django: v4.0.6
 - djangorestframework: v3.13.1
 - djangorestframework_simplejwt: v5.2.0
 - hypothesis: v6.53.0

**Comment by Stranger6667** [comment]
Hi @azeeka 

Unfortunately, Open API 3.0.x defines `requestBody` link behavior as:

> A literal value or {expression} to use as a request body when calling the target operation.

So, it is treated as a literal `{"refresh": "$response.body#/refresh"}` :( [Here](https://schemathesis.readthedocs.io/en/stable/stateful.html#open-api-links-limitations) is a little bit more in the very last section of the docs. 

I want to make it less frustrating, for example with #900 and #1230, but it will require some more time :)

**Comment by azeeka** [comment]
I've come up with a workaround, by experimenting with runtime expression, so I'll leave it here, in case if it may be helpful:
```yaml
          links:
            GetRefreshedTokens:
              operationId: token_refresh_create
              requestBody: '#{refresh: $response.body#/refresh #}'
```

**Comment by rubiodamian** [comment]
Hi, i had the same problem.
i tried a lot of thing and ended using lamda to parse.

define schema links
`schema.add_link(
    source=schema["/api/step1"]["POST"],
    target=schema["/api/step2"]["POST"],
    status_code="200",
    request_body={"data": lambda x: x['stuff']['data']},
    name='mac'
)`

run the stepts as normal:
`    step1 = state.step(
        case=state.schema["/api/step1"]["POST"].make_case),
        previous=None,
    )`

`state.step(
        case=state.schema["/api/step2"]["POST"].make_case(),
        previous=(
            step1
            schema["/api/step1"]["POST"].links['200']['data'],
        ),
    )`

and add a before_call hook:

` def before_call(self, case: Case):
        if case.path == "/api/step2":
            case.body['data'] = case.body['data'](case.source.response.json())
        return case`

i hope it helps

**Comment by fscarlato** [comment]
Hello @rubiodamian but doesn't this gives you test with only one example? How do you iterate it?

**Comment by rubiodamian** [comment]
yes, @fscarlato, just for one example.
but you can make it iterate making each step on init with the initialize decorator
