### ISSUE TITLE
[FEATURE] Possibility to stop test execution after n test failures

### ISSUE THREAD

**Issue by lina-is-here** [schemathesis/schemathesis#1580]
**Is your feature request related to a problem? Please describe.**
In the big and bug-prone APIs it could happen that the schemathesis output is so large it becomes useless.

**Describe the solution you'd like**
Add an option to limit the test failures. For example `--limit-fails=5`. The execution stops after 5 failures.

**Describe alternatives you've considered**
Interrupt execution manually
Redirect output to a file

**Additional context**
That would definitely help to onboard more people.

**Comment by Stranger6667** [comment]
I am leaning toward the `pytest`'s `--maxfail=N` option, or maybe `--max-fail` / `--max-failures` to have more consistent naming
