### ISSUE TITLE
Conda Forge

### ISSUE THREAD

**Issue by thewchan** [schemathesis/schemathesis#1606]
Hello! I have successfully put this package on to Conda Forge, and I have extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/schemathesis-feedstock

**Comment by Stranger6667** [comment]
Hi @thewchan 

Thank you for reaching out! I am interested :) Sure

**Comment by thewchan** [comment]
Thanks @Stranger6667 I will add you as maintainer over there!
