### ISSUE TITLE
[BUG] Confusing error reporting if API responds with SSL errors

### ISSUE THREAD

**Issue by hoog1511** [schemathesis/schemathesis#1607]
**Describe the bug**
with the current stable version of schemathesis i got a test result which stated "no checks are performed". After some debugging it seems this was caused due to an SSL error. I had to revert the schemathesis version to v3.12.3 and rerun the test to get a clear error response. 
The current version of schemathesis does not seem to return this error message, but the older version does (v3.12.3).

**example of the error message given in v3.12.3**
`errors=[requests.exceptions.SSLError(urllib3.exceptions.MaxRetryError("HTTPSConnectionPool(host='abcd.nl', port=443): Max retries exceeded with url: /v1/test (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))")),

=================================== SUMMARY ====================================

No checks were performed.

JUnit XML file: /mountedDir/junit.xml

============================== 1 passed in 0.28s ===============================`

**Comment by Stranger6667** [comment]
Hm, interesting. Such things should be reported. What was the exact version you used that did not report it? If the issue is still there, I'd be keen to improve the status quo by reporting it properly.
