### ISSUE TITLE
[QUESTION] How to authenticate with http-only cookie ?

### ISSUE THREAD

**Issue by triplem161** [schemathesis/schemathesis#1610]
Hello,

I hope you don't mind this question.

I am using FastAPI, and my authentification consist in a http-only cookie being set. Usually sharing a common TestClient is enough to keep the cookie set between requests. But I can't find a way to share a TestClient for the auth request and the case call request. 

I need a context for the TestClient too (`with TestClient(my_app) as session:`), as I need to fire the `startup` and `shutdown` event for the database connection.

Is there a way to share a common session between the auth and the case.call ?

Thanks for your time

**Comment by Stranger6667** [comment]
Hi @triplem161 

Sorry for the delay! Yes, `case.call` accepts a `TestClient` instance as a `session` argument, which is what happens inside the `case.call_asgi` method. I think our doc lacks this detail, I'll add some more examples specifically for Fast API.
