### ISSUE TITLE
[FEATURE] Allow `Werkzeug<=2.2.2`

### ISSUE THREAD

**Issue by stegayet** [schemathesis/schemathesis#1631]
**Is your feature request related to a problem? Please describe.**
Allow `Werkzeug<=2.2.2` to avoid dependency conflicts when using schemathesis alongside `Flask>=2.2.0` 

**Describe the solution you'd like**
Allow `Werkzeug<=2.2.2` 

**Describe alternatives you've considered**
No alternative

**Additional context**
No additional context

**Comment by Stranger6667** [comment]
Fixed by #1630. I'll issue a new release tomorrow
