### ISSUE TITLE
[BUG] no exceptiongroup module found when using python 3.11

### ISSUE THREAD

**Issue by euri10** [schemathesis/schemathesis#1632]
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**

**To Reproduce**

I upgraded a project to python 3.11, and my testsuite broke with this:
```
  File "/home/lotso/.cache/pypoetry/virtualenvs/yoyo-5gvWwsxX-py3.11/lib/python3.11/site-packages/schemathesis/_compat.py", line 40, in <module>
    import BaseExceptionGroup as MultipleFailures
ModuleNotFoundError: No module named 'BaseExceptionGroup'
/home/lotso/.cache/pypoetry/virtualenvs/yoyo-5gvWwsxX-py3.11/lib/python3.11/site-packages/coverage/control.py:801: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
```

Manually adding exceptiongroup solved the issue
```
❯ poetry add exceptiongroup
Using version ^1.0.1 for exceptiongroup

Updating dependencies
Resolving dependencies... (2.0s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing exceptiongroup (1.0.1)
```

**Expected behavior**
Probably have it in the dependencies, not sure 

**Environment (please complete the following information):**

- OS: debian 11
- Python version: 3.11.0
- Schemathesis version: 3.17.3

**Comment by Stranger6667** [comment]
Hi @euri10 

I'll take a look today :) Thank you so much for reporting

**Comment by euri10** [comment]
Yep I arrived at the same conclusion, it's working adding it manually since exceptiongroup detects im on 3.11 and dont uses the backport, but ideally I shouldn't have to install it.

Maybe schemathesis should do the 3.11 detection on requires, I'm not familiar enough with the internals to know,

Thanks for looking at it 🙂

**Comment by Stranger6667** [comment]
You're right! :) The fix will be basically a small condition about Python 3.11, and if it is true, then use the built-in exception class, otherwise check the Hypothesis version & use the backport or `MultipleFailures` from Hypothesis.

**Comment by Stranger6667** [comment]
The issue should be resolved in the next patch release
