### ISSUE TITLE
[FEATURE] CLI option for queries

### ISSUE THREAD

**Issue by hoog1511** [schemathesis/schemathesis#1639]
**Describe the solution you'd like**
I would like to have the option of providing a query value in the CLI to make sure all the tests I perform use this specific value. This query option should function similarly to the --header option that Schemathesis currently has.

**Describe alternatives you've considered**
I have the option of enforcing the values by using an enum instead of an example, and by setting the query to REQUIRED. This however would tell readers of the schema that this value is always used, which is not how the API actually works. I do not want a schema that is just for testing, I want to be able to provide the schema to consumers of the API with the correct context.

**Comment by Stranger6667** [comment]
I think it is a great idea! I'll try to think about the API for it

**Comment by Stranger6667** [comment]
Going to close this one in favor of #1676
