### ISSUE TITLE
[FEATURE] Please unpin `attrs`

### ISSUE THREAD

**Issue by grigi** [schemathesis/schemathesis#1643]
**Is your feature request related to a problem? Please describe.**
`attrs` doesn't strictly stick to semver, is a relatively fast moving project, and stable. Using `schemathesis` restricts getting bugfixes. `attrs` is an extremely popular package and very well tested, it shouldn't be your job as library maintainer to vet each release.

**Describe the solution you'd like**
Please don't pin packages too specifically, as this is a library.

**Describe alternatives you've considered**
Specify `attrs = ">=22.1.0"` in the pyproject.toml file instead of using the caret `^`

**Comment by Stranger6667** [comment]
Hey! 

I agree, probably now it is too restrictive.

> as this is a library.

Many users run it as a CLI as well, so I would not characterize it as a library in all use cases. Though in any case, the current dependency set is not as flexible as I'd like it to be

**Comment by grigi** [comment]
Thanks, looks like your commit: https://github.com/schemathesis/schemathesis/commit/ac69e75ee5e66e0b3c079ed0e4b9b938dabf54ca should resolve this on next release!
