### ISSUE TITLE
[BUG] Schemathesis extremly slow with localhost on windows

### ISSUE THREAD

**Issue by TheBigRoomXXL** [schemathesis/schemathesis#1691]
**Checklist**

- [X] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [X] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
When using localhost to acces the OpenAPI schema like that `st run  http://localhost:5000/openapi.json` it take about one second for every requests. 

I think this is caused by the library **urllib3** as described in this [stackoverflow  question](https://stackoverflow.com/questions/47766158/why-is-python-requests-to-localhost-slow) : 

> the slow connections on Windows were related to urllib3 (the transport library used by requests) attempting an IPv6 connection first, which is refused since the server is listening on IPv4 only. For Windows only, however, there is an unavoidable 1 sec timeout on socket.connect for refused TCP connections, while the OS 'helpfully' retries the connection up to 3 times. (See: [Why do failed attempts of Socket.connect take 1 sec on Windows?](https://stackoverflow.com/questions/19440364/why-do-failed-attempts-of-socket-connect-take-1-sec-on-windows)).
> 
> On Linux, socket.connect fails immediately if the connection is refused, and it can attempt the IPv4 connection without any delay. In addition, some software, like curl, support limiting name resolution to only IPv4 or IPv6. Unfortunately, requests and urllib3 do not support this, and do not seem to plan to support this anytime soon (See: https://github.com/psf/requests/issues/1691)

**To Reproduce**

1. Run this command  `st run  http://localhost:5000/openapi.json` on **Windows**
2. Look at only one request being received by your api every second. 

**Expected behavior**
Pointing to localhost should give the save result as pointing to 127.0.0.1 or else should be documented to avoid any confusion for new users.

**Environment (please complete the following information):**

- OS: Windows
- Python version: 3.10.4 and 3.11
- Schemathesis version: 3.18.3
- Spec version: Open API 3.0.3

**Comment by Stranger6667** [comment]
I guess, it could be at least documented indeed - not sure if we can do something about it without introducing some surprising behavior in other cases.

**Comment by TheBigRoomXXL** [comment]
Thank you for the feedback. 

1 - Would the debugging section be a good place to put it in? 

2 - I did a quick search for `localhost` in the documentation and found a few results. We could swap `localhost` with `127.0.0.1` so that peoples doing copy-past from example don't have any issue. 

If that's OK with you, I can do a PR.

**Comment by Stranger6667** [comment]
I think for now we can put it into a FAQ - there is a plan to build a proper troubleshooting guide, which will derive from FAQ, including this entry.

yep, let’s replace this mentions - you are very welcome to create a PR :)

**Comment by Stranger6667** [comment]
I also suspect that it could be the reason why our test suite is multiple times slower on Windows
