### ISSUE TITLE
[BUG] hypothesis.errors.Unsatisfiable due to shared name

### ISSUE THREAD

**Issue by hoog1511** [schemathesis/schemathesis#1699]
**Describe the bug**
I am having difficulty testing my API with the current stable version of schemathesis for CLI.
The issue for this seems to be caused due to having a header configured as both a parameter and a **securityScheme**, both are also using the same value for **name**. Doing so causes my test to return:
`hypothesis.errors.Unsatisfiable: Unable to satisfy schema parameters for this API operation`

Changing the **name** value for either of the two configurations so they don't match seems to resolve the issue. I have also performed the same test with **v3.17.5** of schemathesis (without changing the **name** value) and there is no issue provided there either.

**To Reproduce**

Test an OAS which uses the following items:
```yaml
 parameters:
    api-key:
      name: TestApiKey
      in: header
      required: true
      description: ApiKey for the API Gateway
      schema:
        type: string
        format: uuid
        pattern: '[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}'
        minLength: 36
        maxLength: 36   
 #################################### 
securitySchemes: 
ApiKeyAuth:
      type: apiKey
      description: "API key to authorize requests."
      name: TestApiKey
      in: header
    oauth2_scheme:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ...
          scopes:
            write:upload_scans: Grants write access for uploading scans 
  security:
    - ApiKeyAuth: []
    - oauth2_scheme:
        - write:upload_scans

```

**Expected behavior**
Test being run without providing me this error.

- OS: Windows
- Python version: 3.11
- Schemathesis version: stable
- Spec version: 3.0.3

**Comment by Stranger6667** [comment]
Hi @hoog1511 

I created the following test from what I read:

```python
from hypothesis import given

import schemathesis


def test_name_clash():
    raw_schema = {
        "openapi": "3.0.2",
        "info": {"title": "Test", "description": "Test", "version": "0.1.0"},
        "paths": {
            "/test": {
                "parameters": [
                    {
                        "name": "TestApiKey",
                        "in": "header",
                        "required": True,
                        "schema": {
                            "type": "string",
                            "format": "uuid",
                            "pattern": "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}",
                            "minLength": 36,
                            "maxLength": 36,
                        },
                    }
                ],
                "get": {"responses": {"200": {"description": "OK"}}},
            }
        },
        "components": {
            "securitySchemes": {
                "ApiKeyAuth": {"type": "apiKey", "name": "TestApiKey", "in": "header"},
                "oauth2_scheme": {
                    "type": "oauth2",
                    "flows": {"clientCredentials": {"tokenUrl": "123", "scopes": {"write:upload": "A"}}},
                },
            }
        },
        "security": [{"ApiKeyAuth": []}, {"oauth2_scheme": ["write:upload"]}],
    }
    schema = schemathesis.from_dict(raw_schema, validate_schema=True)

    @given(case=schema["/test"]["GET"].as_strategy())
    def test(case):
        pass

    test()

```

And I can not reproduce this behavior with Schemathesis at [96a4c0f](https://github.com/schemathesis/schemathesis/commit/96a4c0f39ebc5b3afd8cfa794672a4135126df0a). Running CLI against an equivalent schema does not reproduce this behavior either. However, I run the tests on Mac, but I don't think that it may affect this type of behavior. 

Could you please re-check if I got this schema the way you intended?

P.S. Another thing I noticed is that the `ApiKeyAuth` parameter schema is taken from `securitySchemes` definitions, where Schemathesis uses plain strings, so the UUID schema definition is not taken into account, but I feel it should be as the parameter-level definition is more specific than `securitySchemes`-level.

**Comment by hoog1511** [comment]
Hmm thats odd, because for some reason renaming the **name** field in **securityschemes** (to make it not match the name field of my header) seemed to prevent the error from popping up. I have noticed this error showing up with some other tests of mine with the stable version of schemathesis on other APIs, so I am wondering what the cause might be.

**Comment by Stranger6667** [comment]
I suspect this commit https://github.com/schemathesis/schemathesis/commit/240b6fab0e4865affe5f6c004b4aff8ba04e5075 (mostly a reference for myself to fix it)
