### ISSUE TITLE
I suggest having a CLI option for a custom delay between requests.

### ISSUE THREAD

**Issue by sleek-geek** [schemathesis/schemathesis#1715]
**Is your feature request related to a problem? Please describe.**
Using the CLI is pretty useless when most APIs put a limit on the requests/minute rate.

**Describe the solution you'd like**
I suggest adding a CLI option for a custom delay in seconds between requests, it also would be nice to have an option for adding a proxy list.

**Describe alternatives you've considered**
I tried using the Python library directly, but I would have to go through all cases.

**Additional context**
No such thing.

**Comment by Stranger6667** [comment]
Hi @sleek-geek 

I was thinking about a more full-featured throttling (as briefly touched in #910) - and actually, I have it implemented on top of [PyrateLimiter](https://github.com/vutran1710/PyrateLimiter), but not published it just yet. Adding delays could be done temporarily via the [before_call](https://schemathesis.readthedocs.io/en/stable/extending.html#before-call) hook, but I'll open source throttling soon. Not sure about the public-facing API yet, but it could be something like `--rate-limit=10/m`.
Also, it could be nice to add support for reading response headers and adding delays based on the delay value there.

As for the proxy list - I'd like to have it in the public API too, at the moment proxies could be specified via env variables as in [this recipe](https://schemathesis.readthedocs.io/en/stable/recipes.html#using-an-http-s-proxy)

**Comment by Stranger6667** [comment]
I am going to close this issue in favor of #910 and will add additional context there, also, the proxy list & headers will go to their separate issues to track the progress easier.

**Comment by Stranger6667** [comment]
Btw, here is [an example](https://github.com/schemathesis/schemathesis/issues/910#issuecomment-740468755) of a hook that could be used to add delays between requests.
