### ISSUE TITLE
[FEATURE] Being able to access arrays in a runtime expression syntax

### ISSUE THREAD

**Issue by pycgarcia** [schemathesis/schemathesis#1717]
**Is your feature request related to a problem? Please describe.**
I'm not able to access an array as a part of a response body in the `links` section.

**Describe the solution you'd like**
Something like this should work:
```json
            "links": {
              "someName": {
                "operationId": "getUserById",
                "parameters": {
                  "lookupId": "$response.body[0]"
                } 
              }
            }
```
**Describe alternatives you've considered**
I haven't found any alternative.

**Additional context**
This is crucial for stateful testing since JSON response may contain an array.

As an off-topic comment:
Thank you for this amazing tool, I really appreciate your work and find it very useful!

**Comment by Stranger6667** [comment]
Hi @pycgarcia 

Open API uses JSON pointer which does not use the square brackets syntax. See [examples](https://www.rfc-editor.org/rfc/rfc6901#section-5) in the RFC or in the [Swagger docs](https://swagger.io/docs/specification/links/#examples) (they are relevant for Open API 3.0).

Your expression should be `$response.body.0`

**Comment by pycgarcia** [comment]
Couldn't make it work with dots, found that this is possible:
```
                "parameters": {
                  "lookupId": "$response.body#/0/lookupId"
                } 
```
Than you!

**Comment by Stranger6667** [comment]
You’re welcome:) Oh, yes - I made a mistake :) you’re right
