### ISSUE TITLE
[BUG] CLI reports a failure in the progress bar but not in the report section

### ISSUE THREAD

**Issue by pycgarcia** [schemathesis/schemathesis#1719]
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
I've encountered with two behaviours that seems incorrect.
1. Sometimes (not always) I get a failed (marked as a red F) while running through the CLI, but the final output is that all test passed:
![image](https://user-images.githubusercontent.com/125585094/223965696-38838f48-323e-4e09-8d47-0f277e17cec3.png)
2. After running several POSTs, there are no records of the request in the cassete file. Is there a chance to see the requests that went through? even if they're successful.

**To Reproduce**
Nothing speciall being done.
`st run swagger.json  --hypothesis-max-examples=1 --junit-xml report.xml --validate-schema=true -H {auth} --base-url={URL} -E Addresses --show-errors-tracebacks --cassette-path cassete_path.yaml --report -vvv`

If possible, please post a minimal version of your API schema that cause this behavior:

```yaml
{
    "openapi": "3.0.1"
}
```

**Expected behavior**
Fails have output.
Success are recorded in the cassete yaml.

**Environment (please complete the following information):**

- OS: [e.g. Linux or Windows]
- Python version: [e.g. 3.11.2]
- Schemathesis version: [e.g. 3.18.5]
- Spec version: [e.g. Open API 3.0.1]

**Comment by Stranger6667** [comment]
Hi @pycgarcia ! Friendly bumping this issue - it would be really nice if you could share some more context as this issue definitely a bug in Schemathesis.

**Comment by Stranger6667** [comment]
Closing it as there is not enough info to reproduce it. Feel free to re-open it if the issue persists - any extra info would be much appreciated, e.g. schema
