### ISSUE TITLE
port= not being honored in schemathesis.from_uri() call.

### ISSUE THREAD

**Issue by NAN-CForadas** [schemathesis/schemathesis#1721]
I was testing with a local flask server running APIFlask listening on port 5000.  I got an error when using port=5000.

Using `schema = schemathesis.from_uri('http://127.0.0.1:5000/openapi.json')` works as expected.

Using `schema = schemathesis.from_uri('http://127.0.0.1/openapi.json', port=5000)`  generates the following traceback:

(<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', ***port=80***): Max retries exceeded with url: /openapi.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10738d190>: Failed to establish a new connection: [Errno 61] Connection refused'))")), <traceback object at 0x10738ce80>)

Note `port=80` in the traceback.

**Comment by Stranger6667** [comment]
Hi! Thanks for reporting, will fix it soon!
