### ISSUE TITLE
[BUG] FastAPI App lifespan hook doesn't get run

### ISSUE THREAD

**Issue by Joeboy** [schemathesis/schemathesis#1727]
**Checklist**

- [✓] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [✓] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
It seems that if I use a [lifespan](https://fastapi.tiangolo.com/advanced/events/) with my schemathesis test, it doesn't get called, which results in my tests failing. I think this would also be the case with the deprecated startup / shutdown event hooks (I admittedly didn't check).

**To Reproduce**

Use the "Python tests" example from the README:

```
import schemathesis

schema = schemathesis.from_uri("https://example.schemathesis.io/openapi.json")


@schema.parametrize()
def test_api(case):
    case.call_and_validate()
```

If possible, please post a minimal version of your API schema that cause this behavior:

N/A

**Expected behavior**
App lifespan hook is run. Or maybe more test setup is required? I see various related discussion, and a package called `asgi-lifespan` which seems vaguely related, but it's not obvious to me how I might get this working, or even if it's possible.

**Environment (please complete the following information):**

- OS: Ubuntu Linux
- Python version: 3.9
- Schemathesis version: 3.19.0
- Spec version: OpenAPI 3.0.2

**Additional context**

Trying to test a FastAPI app that has [TiMVT](https://github.com/developmentseed/timvt) mounted.

**Comment by Stranger6667** [comment]
This is indeed an issue with the current approach to ASGI, I am going to rework our ASGI documentation and sort all related issues out for Schemathesis 3.21
