### ISSUE TITLE
[BUG] Issue with --hypothesis-phases=explicit and GET requests without parameters

### ISSUE THREAD

**Issue by Chamarez** [schemathesis/schemathesis#1728]
**Description:**

When using the --hypothesis-phases=explicit parameter in SCHEMATHESIS, it has been observed that GET requests without parameters are being skipped during testing. This creates a problem for users as they have to resort to adding fake parameters and then try to exclude them from the documentation, which is not an optimal solution.

The example that reproduces the error:
```
paths:
  /books:
    get:
      security: []
      summary: books
      description: Get list of books
      tags:
        - "books"
      operationId: get_books
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
```

Example with fake param:
```
paths:
  /books:
    get:
      security: []
      summary: books
      description: Get list of books
      tags:
        - "books"
      operationId: get_books
      parameters:
        - name: fake
          in: query
          description: Fake param for schemathesis
          schema:
            type: string
          required: false
          examples:
            fake:
              value: fake
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
```

**To Reproduce**
Add a get petition without params and use the --hypothesis-phases=explicit configuration.
Schemathesis will skip this test.

**Expected behavior**
Execute gets requests without params.  

**Environment :**
Docker container,  image: schemathesis/schemathesis:stable

**Comment by IvanRibakov** [comment]
Hi @Stranger6667, this issue is somewhat painful and stops us from transitioning from dredd to schemathesis with piece of mind. I'd be willing to try to put together a PR if you could give some pointers where to start as I'm not familiar with schemathesis/hypothesis internals.

**Comment by IvanRibakov** [comment]
@Stranger6667 Thank you for the expanded answer. Now I can see why you've applied "Needs Design" label. I'm afraid working on a proper solution according to the vision that you laid out above is out of my depth, but I have to say that the workaround that you mentioned works well for us - thanks for sharing it!

**Comment by Stranger6667** [comment]
@IvanRibakov 

You're very welcome!

No worries, I am going to make a PR for this `contrib` feature soon and hopefully ship it before the end of the week.

**Comment by Stranger6667** [comment]
I added `--contrib-openapi-fill-missing-examples` that enables the hook above, so it should provide the capability :) Re: shipping a new release - I think to implement some more fixes related to explicit examples before making a new release. Not sure about the estimation though.
