### ISSUE TITLE
Provide an ARM based Docker image

### ISSUE THREAD

**Issue by t1** [schemathesis/schemathesis#1740]
When I run the docker image on my Mac, it has to emulate the AMD/Intel processor using Rosetta, which makes it slow. The experience would be much nicer, if there was a Docker image based on arm64 architecture.

Multi-architecture builds are well supported by all current toolchains I'm aware of, so the actual change required is probably minimal... but the impact on more and more users (not only Apple) would be substantial.

**Comment by Stranger6667** [comment]
I am up for providing them :) However, I need to check whats are the current best practices for it (anyone providing some useful links are welcome)
