### ISSUE TITLE
[DOCUMENTATION] how to use graphql schema get_case_strategy

### ISSUE THREAD

**Issue by devkral** [schemathesis/schemathesis#1754]
I found no documentation how I can use the get_case_strategy of graphql schema to only test queries or just a subset.

Can you please expand the documentation or point out where I find the information?

**Comment by Stranger6667** [comment]
Sorry for the late reply!

There was no way to filter API operations for GraphQL, so I added a `filter_operations` hook to make it possible. However, filters are not yet supported in CLI, which I am going to implement separately for all schema types in a unified way.

See the docs here - https://github.com/schemathesis/schemathesis/blob/master/docs/extending.rst#filtering-api-operations
