### ISSUE TITLE
Add convenience methods on `ParameterSet`

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#1789]
It could be useful in hooks, e.g. to check whether `APIOperation` contains some header (we leave case-insensitive for a while). 

1. Add a new `contains` method to the [ParameterSet](https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/parameters.py#L55) class, the method should accept `name` of type `str`
2. The implementation should reuse the `get` method and check whether its result is `None`
3. Inside `test/specs/openapi/parameters/test_simple_payloads.py` add a new function `test_parameter_set_get`
4. This test function could have a setup like this:

```python
import schemathesis

# ... other tests omitted for brevity

def test_parameter_set_get(make_openapi_3_schema):
    header = {"in": "header", "name": "id", "required": True, "schema": {}}
    raw_schema = make_openapi_3_schema(parameters=[header])
    schema = schemathesis.from_dict(raw_schema)
```

5. Use the new method from step 1 on `schema["/users"]["POST"].headers` inside this test and verify that it contains the header with the name `id` and does not contain the header with the name `unknown`

**Comment by EkaterinaZaritskaia** [comment]
Hi, I'll try to solve it
