### ISSUE TITLE
[schemathesis]Why  there is no setup.py in  V 3.19.7

### ISSUE THREAD

**Issue by RayLXing** [schemathesis/schemathesis#1848]
Why  there is no setup.py in  V 3.19.7
https://pypi.org/simple/schemathesis/

**Comment by Stranger6667** [comment]
The project moved to PEP621 a while ago and uses only pyproject.toml

**Comment by RayLXing** [comment]
How to install use this way "python setup.py install"?
（Background: I couldn't install using the PIP command due to network limitations and had to install using the python command）
