### ISSUE TITLE
[BUG][schemathesis]Why there is no setup.py in V 3.19.7

### ISSUE THREAD

**Issue by RayLXing** [schemathesis/schemathesis#1849]
How to install use this way "python setup.py install"?
（Background: I couldn't install using the PIP command due to network limitations and had to install using the python command）

**Comment by Stranger6667** [comment]
The setup.py installation method is not supported and there are no plans to bring it back. I would suggest using most recent pip versions that should support installing without network access. In any event, I don’t think there is anything to do from the Schemathesis side
