### ISSUE TITLE
[FEATURE] Use `anyio`, so that ASGI support works for both asyncio and Trio

### ISSUE THREAD

**Issue by Zac-HD** [schemathesis/schemathesis#1872]
The support for directly testing ASGI apps is really nice, but at the moment it doesn't support Trio - so I can't use it 😢 

Fortunately this is pretty easy to fix by using `anyio`, a compatibility layer which can be run against either asyncio or Trio backends; it's already widely used by e.g. httpx and starlette/fastapi.  What that would look like:

https://github.com/schemathesis/schemathesis/blob/8c4fe09c94e65cec9814d8e36fdf379e2810db43/src/schemathesis/_hypothesis.py#L99-L106

```python
 def make_async_test(test: Callable) -> Callable: 
     def async_run(*args: Any, **kwargs: Any) -> None:
        return anyio.run(partial(test, *args, **kwargs))
  
     return async_run 
```

I think the main effort here would actually be to test something on trio as well as asyncio, which shouldn't be too hard to parametrize.

**Comment by Zac-HD** [comment]
IIRC aiohttp is asyncio-specific, so you might need to switch that out for httpx.  pytest-anyio may also be helpful?

**Comment by Stranger6667** [comment]
In the next release, `@pytest.mark.trio` and other ways of enabling trio support from `pytest-trio` will work :tada:
