### ISSUE TITLE
[FEATURE] upgrade tox, pre-commit basepython to 3.10 or 3.11

### ISSUE THREAD

**Issue by devkral** [schemathesis/schemathesis#1971]
python3.9 is nearly EOL. So it would be nice to have some later python versions for development

**Comment by Stranger6667** [comment]
I would not consider 2025-10 as EOL, but I'd bump the versions, sure

**Comment by Stranger6667** [comment]
Except maybe for the `pytest53` tox job, as Python 3.10 is not supported by that old pytest version. On the other hand, it might be the time to drop support for a 4yo `pytest` version

**Comment by devkral** [comment]
I hadn't the exact date in head, but django switched because of such a reason (python3.9 becomes EOL while support range).
