### ISSUE TITLE
[BUG] documentation how cool hooks are

### ISSUE THREAD

**Issue by devkral** [schemathesis/schemathesis#1977]
### Describe the bug

There is no documentation how cool hooks are:

instead of using global hooks you can define hooks directly with your schema and have some different sets of hooks for different tests  this way

e.g.

```python

@schema.hook
def hook_name(...):
   ...
```

Note: the function name is important (it must equal the hook name to receive its parameters) but documented.

For example the filter_query hook can decide if a query should be used

**Comment by Stranger6667** [comment]
I appreciate your take on hooks and the desire to document them! But it feels like the aspects you are mentioning are addressed in the [Hooks sub-section](https://schemathesis.readthedocs.io/en/stable/extending.html#hooks) of the docs on extending Schemathesis, specifically:

> Hooks are applied at different scopes: global, schema-specific, and test-specific. They execute in the order they are defined, with globally defined hooks executing first, followed by schema-specific hooks, and finally test-specific hooks.

```python
import schemathesis


@schemathesis.hook("filter_query")
def global_hook(context, query):
    return query["key"] != "42"


schema = schemathesis.from_uri("http://0.0.0.0:8080/swagger.json")


@schema.hook("filter_query")
def schema_hook(context, query):
    return query["key"] != "43"


def function_hook(context, query):
    return query["key"] != "44"


@schema.hooks.apply(function_hook)
@schema.parametrize()
def test_api(case):
    ...
```

The naming aspect is also addressed in the previous paragraph:

> Hooks are identified and applied based on their function name, utilized through a decorator, like @schemathesis.hook. The function name, such as filter_query, indicates it’s a hook to filter query parameters. When dealing with multiple hooks that serve similar purposes, especially across different schemas within the same file, custom names can be assigned as the first argument in the decorator to avoid conflicts and maintain clarity.

```python
import schemathesis


@schemathesis.hook
def filter_query(context, query):
    return query["key"] != "41"


@schemathesis.hook("filter_query")
def avoid_42(context, query):
    return query["key"] != "42"


@schemathesis.hook("filter_query")
def avoid_43(context, query):
    return query["key"] != "43"
```

If you feel there are more aspects that can be added there, please, feel free to re-open the issue

Thanks!

**Comment by devkral** [comment]
if given a string a decorator is returned and you can have multiple hooks for the same purpose. This is even better ;)

**Comment by devkral** [comment]
thx for the explaination
