### ISSUE TITLE
[FEATURE] allow selecting Type as strategy for graphql schemas

### ISSUE THREAD

**Issue by devkral** [schemathesis/schemathesis#1982]
Thanks for the great improvements to the graphql schemas. I have a little suggestion how to select the operation:

Would it be possible to subclass the dict used for graphql_schema["Operation"] and provide a as_strategy method?

This would allow intuitively selecting an operation and test all fields.

Example:

```python
graphql_schema["Query"].as_strategy()

```
This shortcut would maybe be nice for openapi too and could allow feature parity with the existing @parameterize decorator.

Further thought: would it also be possible to implement an as_strategy method directly on a schema (to test everything without selecting)?

**Comment by Stranger6667** [comment]
Great idea! On it

**Comment by Stranger6667** [comment]
> Further thought: would it also be possible to implement an as_strategy method directly on a schema (to test everything without selecting)?

Yep
