### ISSUE TITLE
[FEATURE] graphql not required handling

### ISSUE THREAD

**Issue by devkral** [schemathesis/schemathesis#1994]
Currently when fields in graphql schemas are not required, schemathesis can send `null` to them.
According to the graphql specs this is valid and it is useful to find bugs.

But sometimes it would be easier to not send null values

Is there a way to turn the null value sending behavior off? It would be nice to have a simple switch for it

**Comment by Stranger6667** [comment]
I see it this way.

First, it should be added to `hypothesis-graphql`, ie. some argument to the [strategy factories](https://github.com/Stranger6667/hypothesis-graphql/blob/master/src/hypothesis_graphql/_strategies/strategy.py#L471) like `allow_null: bool = True`, then store it on the `GraphQLStrategy` instance and use it [here](https://github.com/Stranger6667/hypothesis-graphql/blob/master/src/hypothesis_graphql/_strategies/strategy.py#L77) to enforce non-nullability during data generation (i.e. before passing this to `primitives.scalar`, etc)

Second, this option should be added to Schemathesis CLI & other entry points to propagate it down via `as_strategy` to `hypothesis-graphql`

**Comment by Stranger6667** [comment]
In the next release you could use `--generation-graphql-allow-null=false` for this purpose.
