### ISSUE TITLE
schemathesis and fastapi with elasticsearch

### ISSUE THREAD

**Issue by navik86** [schemathesis/schemathesis#2120]
Hi. Someone tested the compatibility of this:

schemathesis==3.26.0
fastapi==0.104.1
elasticsearch[async]<=8.0.0

Problem: Strange behavior with opening/closing the loop.
For a moment, the connection to the elastic  is in the closed loop and test failed.

For example:
id elastic.transport.loop - 46912948386512 <_Unix SelectorEventLoop started=False closed=True debugging=False>
id get_event_loop - 46912936546320 <_Unix SelectorEventLoop started=True closed=False debugging=False>

It should be the same thing.

**Comment by Stranger6667** [comment]
Hi @navik86 

Could you please share some specific reproduction sample?

**Comment by Stranger6667** [comment]
The traceback is helpful but does not give me a way to reproduce the issue

**Comment by navik86** [comment]
I can't share this project.

**Comment by Stranger6667** [comment]
Then I can't do anything without a way to reproduce the issue, as it is not specific nor actionable from the given description. I don't know how you set up your tests and don't have the time to do the guesswork as there could be tons of conditions that may lead to the behavior you observe.

However, it is not necessary to share the project per se, you may try to build a **minimal** case that uses similar dependencies, but not necessarily the same code as you have in your project. Another alternative is to share the repro sample in private if it works for you (e.g. in Discord)

There are also specific bug report templates that you did not use for some reason. It contains specific questions so I don't have to ask them all manually in separate comments, so both of us can save time.

**Comment by lschneidpro** [comment]
I'm encountering the same issue with FastAPI and async Elasticsearch, specifically with the event loop being closed. I believe it's related to this: [GitHub issue](https://github.com/schemathesis/schemathesis/issues/1718). Is there an example of running tests with `httpx.AsyncClient()`?

Even though I'm in a corporate environment, I'm willing to provide a minimal reproducible example.

**Comment by lschneidpro** [comment]
@Stranger6667 could you reopen the issue ?

**Comment by navik86** [comment]
I resolved this.
```
aes = AsyncElasticsearch(...) # global client for app

class AsyncAESContextManager:
    def __init__(self):
        self.aes = AsyncElasticsearch(hosts=settings.ELASTIC.LIST_DSN) # temporary client for shemathesis

    async def __aenter__(self):
        return self.aes

    async def __aexit__(self, exc_type, exc, tb):
        await self.aes.close()


async def get_connection_elastic():
    if not settings.TEST_MODE:
        yield aes
    else:
        async with AsyncAESContextManager() as test_aes:
            yield test_aes
```

**Comment by lschneidpro** [comment]
Thanks @navik86 
I'm already running some integration tests with `httpx.AsyncClient()`. So wondering if it is would be an easier way to fix it.

**Comment by lschneidpro** [comment]
@navik86 How do you consume later `async def get_connection_elastic()` since its a generator ? thanks

**Comment by navik86** [comment]
@lschneidpro 
```
def get_some_service(
    aes: AsyncElasticsearch = Depends(get_connection_elastic),
) -> SomeService:
    ...
```

**Comment by lschneidpro** [comment]
ok so you initialize the es client for each request. I have a different setup where the es_client is set up when the app is created...

**Comment by navik86** [comment]
@lschneidpro initialize the es client for each request only for shemathesis tests. For normal app work one constant client.
