### ISSUE TITLE
[BUG] Setting body after make_case() causes request to be sent without a body

### ISSUE THREAD

**Issue by simonhammes** [schemathesis/schemathesis#2208]
First off: Great library :100: 

---

### Checklist

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [x] I am using the latest version of Schemathesis

### Describe the bug
The body is not sent if it is manipulated **_after_** calling `make_case()`. Setting `body` when calling `make_case()` works.

Related: https://github.com/schemathesis/schemathesis/issues/1094, https://github.com/schemathesis/schemathesis/issues/1188

### To Reproduce

```python
import schemathesis
from schemathesis import Case

schema = schemathesis.from_path(
    './petstore.yaml',
    base_url='http://127.0.0.1:4010',
    validate_schema=True,
)

def test_api():
    # This does not work:
    add_pet: Case = schema.get_operation_by_id('addPet').make_case() 
    add_pet.body = {'name': 'ABC'}
    response = add_pet.call_and_validate()
    # This will print None
    print(response.request.body)

    # This works instead:
    add_pet: Case = schema.get_operation_by_id('addPet').make_case(body={'name': 'ABC'})
    response = add_pet.call_and_validate()
    # This will print the request body
    print(response.request.body)

    # Capture stdout
    assert False
```

🚨 **Mandatory** 🚨: Steps to reproduce the behavior:

1. Download OpenAPI specification
2. Start mock server (e.g. using [Prism](https://github.com/stoplightio/prism))
3. pytest main.py

Please include a minimal API schema causing this issue:

https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml

### Expected behavior

The body should be sent since the media type is specified in the OpenAPI specification.

### Environment

```
- OS: Linux
- Python version: 3.12
- Schemathesis version: 3.28.1
- Spec version: OpenAPI 3.0.0
```

**Comment by Stranger6667** [comment]
@simonhammes 

Thank you! I've been busy with other issues, but I hope to get back to this in a week or so. Sorry for the delay.

**Comment by Stranger6667** [comment]
The fix will be available in the next release
