### ISSUE TITLE
[BUG] OpenAPI/Swagger 2.0 : property level example values are not working

### ISSUE THREAD

**Issue by ravy** [schemathesis/schemathesis#2277]
### Checklist

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [x] I am using the latest version of Schemathesis

### Describe the bug

In an application, we give property level examples for an object, but the example values
are not being considered as a test case with option --hypothesis-phases=explicit

### To Reproduce

1. save given api schema as testopenapi20.yaml
2. Run this command ```
st run -v --hypothesis-phases=explicit --validate-schema=true -c all --hypothesis-verbosity=debug --base-url=http://localhost:8083 --dry-run testopenapi20.yaml```
3. See error, lack of two examples, you see only single case as below
Case(headers={'Authorization': ''}, body={'title': 'Reading', 'description': 'Read a comic'})

Please include a minimal API schema causing this issue:

```yaml
swagger: "2.0"
info:
  version: 0.1.0
  title: Item List API
  license:
    name: Test
schemes:
  - http
host: localhost:8083
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
paths:
  /items:
    post:
      summary: Add a new item to the list
      operationId: addItem
      tags:
        - items
      parameters:
        -
          in: body
          name: Item
          required: true
          description: item object for POST body
          schema:
            $ref: "#/definitions/Item"
      responses:
        "201":
          description: Item added successfully
          schema:
            $ref: "#/definitions/Item"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/Error"
        "401":
          description: Access token is missing or invalid
      consumes:
        - application/json
      produces:
        - application/json
      security:
        -
          ApiKeyAuth: []
definitions:
  Items:
    items:
      $ref: "#/definitions/Item"
    type: array
  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
      data:
        type: object
  Item:
    type: object
    required:
      - title
      - description
    properties:
      id:
        type: string
        description: ID of the list item.
        format: uuid
        example: "415feabd-9114-44af-bc78-479299dadc1e"
      title:
        type: string
        description: Title of the item.
        example: Learn Music
      description:
        type: string
        description: More detailed description of the item.
        example: learn to play drums
      year:
        type: string
        description: Target year
        pattern: ^\d{4}
        example: 1987
    example: 
      title: "Reading"
      description: Read a comic
```

### Expected behavior

Expecting two examples to be tested.

### Environment

```
- OS: Linux
- Python version: 3.9.18
- Schemathesis version: 3.29.2 (hypothesis-6.103.1, hypothesis_jsonschema-0.23.1, jsonschema-4.22.0)
- Spec version: Open API 2.0
```

### Additional context

went through the documentation (twice), there is no mention that property level example values are not supported. 
even after removing the explicit example with title "Reading", the other example from properties is not considered.
tried removing the quotation marks for each example, did not make a difference

**Comment by Stranger6667** [comment]
@ravy thank you very much for opening the issues and for filling them with such high level of details. These are certainly bugs and I’ll take a look at them over this weekend.
