### ISSUE TITLE
[BUG] Links being followed on example tests

### ISSUE THREAD

**Issue by ravy** [schemathesis/schemathesis#2376]
### Checklist

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [x] I am using the latest version of Schemathesis

### Describe the bug

I see that links are being followed even when i specify `--hypothesis-phases=explicit`
minor issue, but even if filter out API using `--include-name` they are still followed
guessing `--include-name` means run only that and not follow links?!
or maybe not follow them when `--hypothesis-phases=explicit`
understand them being followed for stateful testing however

the problem with links being followed on stateless/example testing is for example:
assume `POST /trees`  is linked to `DELETE /trees/id` with the id from creation used for the delete.
when `--hypothesis-phase=explicit` then the state/id from POST call is _not_ used for the DELETE
instead any explicit example id under `DELETE /trees/id` are used for the linked test.
hope my explanation is clear with this example

### To Reproduce

1. Run this command `st run --include-name 'POST /trees' tree-openapi20.yaml --base-url=http://localhost:8083 --hypothesis-phases=explicit`
2. See links are followed

Please include a minimal API schema causing this issue:
`any schema with links and examples`

### Expected behavior
_imho_
1. links not followed when `--hypothesis-phases=explicit` specified
2. `--include-name` honored and linked not followed if not in the inclusion

### Environment
`platform Linux -- Python 3.9.18, schemathesis-3.33.1, hypothesis-6.108.2, hypothesis_jsonschema-0.23.1, jsonschema-4.23.0`

**Comment by ravy** [comment]
maybe this is relevant:
this issue is seen only when actual webserver is serving the api, not seen when api is not implemented or with `--dry-run`

**Comment by Stranger6667** [comment]
Hi! Thanks for reporting! Do you use the new-style stateful testing or the one enabled by default right now? I see from the command that there is no `--experimental=stateful-test-runner`, so I assume the latter.

For the new-style stateful testing, it should be properly filtered as the operations are being filtered during state machine creation, but apparently, the old version does not respect it. I'll take a look soon
