### ISSUE TITLE
[FEATURE] What is the recommended way to add different authentication methods?

### ISSUE THREAD

**Issue by fomcl** [schemathesis/schemathesis#2458]
### Is your feature request related to a problem? Please describe

Clearly state the issue you're facing. How often does this occur? What's the impact?

* Our API uses Kerberos authentication, which isn't supported. Looking at the [source](https://github.com/schemathesis/schemathesis/blob/f30fafde50487849f1d191600126ee8bf1ab603e/src/schemathesis/transports/auth.py#L13) it seems like I just monkey-patch a function so it works with `requests_kerberos`. I'll try that. But what's the recommended way to do this?

### Describe the solution you'd like

Clearly describe what you want to happen.

* A not so quick-and-dirty solution. Alternatively, a _Recipes_ section in the docs that demonstrate how to use different auth methods.

### Describe alternatives you've considered

Have you tried any workarounds? Describe alternative solutions or features.

* Monkey-patching, see above

### Additional context

Include any other context, like use-cases, diagrams, or screenshots, to help us understand the feature request.

**Comment by Stranger6667** [comment]
Hi! Have you checked the `Authentication` docs? I believe it should cover your use case. If it does not, please, do let me know, otherwise I'll update FAQ, so it is easier to find the docs for auth (or maybe update docs index too)

https://schemathesis.readthedocs.io/en/stable/auth.html#third-party-implementation

**Comment by fomcl** [comment]
Perfect, thanks a lot! I checked the CLI documentation, which mentions only basic and digest auth. So it might help to also mention the 3rd party there. Thanks again, I appreciate it!

**Comment by Stranger6667** [comment]
Thank you! Adjusted the docs in 30d296d43a329bfe633c4c06d2e7161976692fc0
