### ISSUE TITLE
[BUG] openAPI auth bearer auth issue

### ISSUE THREAD

**Issue by b3n4kh** [schemathesis/schemathesis#2462]
### Checklist

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [x] I am using the latest version of Schemathesis

### Describe the bug

While using an openAPI schema with a securityscheme of type bearer: https://swagger.io/docs/specification/authentication/bearer-authentication/ I get the following error:

```
E       schemathesis.exceptions.CheckFailed:
E
E       1. Authentication declared but not enforced for this operation
E
E           The API returned `200 OK` for `GET /<PATH>` with invalid auth.
E
E       [200] OK:
E
E           `[]`
E
E       Reproduce with:
E
E           curl -X GET -H 'Authorization: [Filtered]' http://localhost/api/dashboard/trending-clusters
```

The authentication is however valid (therefore the 200 response)

The error is triggered by this codeblock: https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/specs/openapi/checks.py#L368C1-L372C1

Only if ignored_auth check is enabled.

This happens because `_contains_auth` returns  `AuthKind.GENERATED` which happens since ctx inside contains auth is always None. Which is as far as I could see a result of the securityscheme type.

It doesn't matter if I pass the authentication directly to call_wsgi() via headrs=<authheader> or if I set it via a @schema.auth() decorator. Both send the correct header and successfully authenticate, but the `ignored_auth` check fails. In the case of directly set headers, because `parameter["name"] in ctx.headers` fails if set via the decorator because ctx is None.

### To Reproduce

🚨 **Mandatory** 🚨: Steps to reproduce the behavior:

1. Run this command:

```python
app = create_app()
schemathesis.experimental.OPEN_API_3_1.enable()
schema = schemathesis.from_wsgi("/api/doc/swagger.json", app, skip_deprecated_operations=True)

@schema.auth()
class UserAuth:
    def get(self, case, context):
        client = werkzeug.Client(context.app)
        response = client.post("/api/auth/login", json={"username": "admin", "password": app.config["PRE_SEED_PASSWORD_ADMIN"]})
        if not response or not response.json:
            raise AssertionError(response.text)
        return response.json["access_token"]

    def set(self, case, data, context):
        case.headers = case.headers or {}
        case.headers["Authorization"] = f"Bearer {data}"



@schema.parametrize(endpoint="^/api/dashboard")
@settings(max_examples=50, suppress_health_check=(HealthCheck.function_scoped_fixture,))
def test_dashboard(case):
    response = case.call_wsgi()
    case.validate_response(
        response,
        checks=(ignored_auth),
    )
```

2. See error

Please include a minimal API schema causing this issue:

See [taranis-ai/openapi3_1.yaml](https://github.com/taranis-ai/taranis-ai/blob/master/src/core/core/static/openapi3_1.yaml) for a more comprehensive example

```yaml
openapi: 3.1.0
security:
  - APIKey: []
  - UserAuth: []

paths:
  /dashboard:
    get:
      description: get trending clusters
      security:
        - UserAuth: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    size:
                      type: integer
                    name:
                      type: string
                    tags:
                      type: array
                      items:
                        type: object
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '404':
          $ref: "#/components/responses/404NotFound"
        '500':
          description: Internal server error
 
components:
  securitySchemes:
    APIKey:
      type: http
      in: header
      scheme: bearer
      bearerFormat: APIKEY
    UserAuth:
      type: http
      in: header
      scheme: bearer
      bearerFormat: JWT

  responses:
    404NotFound:
      description: "Not found response"
    401Unauthorized:
      description: authorization error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    405MethodNotAllowed:
      description: method not allowed

```

### Expected behavior

Since I send a valid authentication header a valid response should be expected.

### Environment

```
- OS: Linux Fedora 40
- Python version: 3.12
- Schemathesis version: 3.36.0
- Spec version: 3.1.0
```

### Additional context

Removing igonred_auth from the checks works as a workaround right now.

**Comment by b3n4kh** [comment]
Running the exact same code with schemathesis 3.35.0 does not trigger this bug.

**Comment by Stranger6667** [comment]
@b3n4kh Thank you so much for opening the issue and investigating the cause! Much appreciated!

The issue is that custom auth was not considered at all when detecting explicit auth. Will fix it soon

**Comment by Stranger6667** [comment]
I also think that regular non-custom auth should not be affected at all. Please, let me know if I am missing something and the fix is not sufficient

**Comment by pregress** [comment]
I still have this issue, with v 3.36.1.

Run in docker, but with `--experimental=stateful-test-runner` 
Not using the experimental stateful-test-runner fixes this

Related openapi spec:

```(yaml)
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
```

**Comment by Stranger6667** [comment]
@pregress Thanks! I'll re-check it. Can you confirm, that the issue happens during stateful tests specifically? Or it affects the non-stateful part.

**Comment by pregress** [comment]
Output:

```
2024-09-26T06:34:58.801614601Z Stateful tests
2024-09-26T06:34:58.801616874Z 
2024-09-26T06:37:24.529131283Z F.....................................................................................................................................................
2024-09-26T06:37:32.835049844Z 
2024-09-26T06:37:32.835098198Z 
2024-09-26T06:37:32.835101059Z =================================== FAILURES ===================================
2024-09-26T06:37:32.835103995Z ________________________________ Stateful tests ________________________________
2024-09-26T06:37:32.836204839Z 1. Test Case ID: 698sSf
2024-09-26T06:37:32.836239843Z 
2024-09-26T06:37:32.836242895Z - Authentication declared but not enforced for this operation
2024-09-26T06:37:32.836245469Z 
2024-09-26T06:37:32.836247095Z     The API returned `200 OK` for `GET /redacted/redacted` with invalid auth.
2024-09-26T06:37:32.836249218Z 
2024-09-26T06:37:32.836251207Z [200] OK:
2024-09-26T06:37:32.836257250Z 
2024-09-26T06:37:32.836261364Z     `[{"id":"REDACTED // Output truncated...`
2024-09-26T06:37:32.836278103Z 
2024-09-26T06:37:32.836296030Z Reproduce with: 
2024-09-26T06:37:32.836310005Z 
2024-09-26T06:37:32.836317294Z     curl -X GET -H 'Authorization: [Filtered]' http://redacted:8080/redacted/redacted
2024-09-26T06:37:32.836323632Z 
2024-09-26T06:37:32.836325566Z =================================== SUMMARY ====================================
2024-09-26T06:37:32.836342159Z 
```

**Comment by pregress** [comment]
@Stranger6667 Is it better to create a new issue for this, or put it in the discussion of the stateful test runner? (https://github.com/schemathesis/schemathesis/discussions/2262)

**Comment by Stranger6667** [comment]
@pregress A new issue would be better :) re-checking it is on my todo list for this week
