### ISSUE TITLE
[FEATURE] Option to case sensitive compare response schema conformance

### ISSUE THREAD

**Issue by pregress** [schemathesis/schemathesis#2474]
### Is your feature request related to a problem? Please describe

We expose apis that are consumed in low level languages on embedded devices and hence we would like to validate compliance that the response schema matches the casing. So we can deploy more confidently knowing not breaking contract. 

### Describe the solution you'd like

Provide an option to validate the response schema with case sensitivity eg: `--case-sensitive` 
I think this could be handled here: https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/specs/openapi/schemas.py#L650

### Describe alternatives you've considered

Doing string comparison in tests for casing in schemas is a pain in the but. 

### Additional context

N/A

**Comment by Stranger6667** [comment]
Could you, please elaborate on what string comparison should happen in a case-insensitive manner? Some examples would help a lot. Generally, I don't think there is a notion of string casing in JSON Schema at all as it could be applied in many places (i.e. enums, patterns, patternProperties, etc)

**Comment by pregress** [comment]
Let's say you have the following schema in openapi:

```(yaml)
Product:
      type: object
      properties:
        Id:
          type: integer
```

And the API response is something like 
```(json)
{"id":1}
```


Since `Id` is starting with an uppercase I and the response is not, it would be good to report this. But not break compatibility with current behavior.

**Comment by Stranger6667** [comment]
Thank you for sharing! 

> Since Id is starting with an uppercase I and the response is not, it would be good to report this

If you have `required` in this schema, it will be reported as missing `Id` property. Also, having `additionalProperties: false` will notify you about having unknown properties. Would it be sufficient for your use case?

Otherwise, the conformance check follows the semantics of JSON Schema, where the `properties` keyword checks exact keys, i.e. it _is_ case sensitive.

**Comment by pregress** [comment]
Ok, thanks for the info, additionalProperties and required indeed solves it.
