### ISSUE TITLE
[BUG] Schemathesis is extremely slow in the GitHub Actions CI (WeeChat project)

### ISSUE THREAD

**Issue by flashcode** [schemathesis/schemathesis#2507]
### Checklist

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [x] I am using the latest version of Schemathesis

### Describe the bug

Schemathesis is extremely slow in the WeeChat GitHub Actions CI.

### To Reproduce

🚨 **Mandatory** 🚨: Steps to reproduce the behavior:

1. Run the WeeChat CI (Actions), master branch.
2. The API tests take ~ 45-50 minutes.

CI example: https://github.com/weechat/weechat/actions/runs/11316004676/job/31467847809 (see Test Relay OpenAPI).

### Expected behavior

The API tests take approximately 43 seconds (like when we run them locally).

CI example: https://github.com/weechat/weechat/actions/runs/11232564012/job/31224422504 (see Test Relay OpenAPI).

### Environment

```
- OS: Linux Ubuntu 22.04 or 24.04 (GitHub CI)
- Python version: 3.10.12
- Schemathesis version: 3.37.0
- Spec version: OpenAPI 3.1.0
```

### Additional context

I can not reproduce the issue on my workstation, it only takes huge time inside GitHub Actions.
As the GitHub Actions OS was recently updated, this might be related to the issue: the last run that took 43 seconds was done before the GitHub Actions OS upgrade.

I tried 3 things, without positive effect:

1. switch from Ubuntu 22.04 to 24.04
2. use `127.0.0.1` instead of `localhost` in the URL used by schemathesis
3. use schemathesis 3.36.4 instead of 3.37.0.

I'm not sure at all this is an issue with schemathesis itself as I can't reproduce locally, but if you have any idea of the cause of the issue, or it you can give me tips to troubleshoot the slowness, they are welcome, thanks!

**Comment by Stranger6667** [comment]
Hey! Thanks for reporting!

Today I’ve got some perf regressions from the recent Hypothesis update, so it is my first suspect - https://codspeed.io/schemathesis/schemathesis/branches/dependabot/github_actions/github/codeql-action-3.26.12.

I on vacation right now and will take a closer look when I am back in a few days. If my assumption is correct then temporary pinning the hypothesis version should help

**Comment by Stranger6667** [comment]
Suspected release - https://github.com/HypothesisWorks/hypothesis/commit/8a014831480d22a824e1266d9aabdb751f33f1de

**Comment by flashcode** [comment]
Thanks @Stranger6667, good catch!

I can confirm it works fine with hypothesis 6.114.1 and it becomes extremely slow with version 6.115.0 (tested locally).

Should I report the issue in their repository?

**Comment by phknot** [comment]
Can confirm we are experiencing the same issue. Pipelines are taking over 90 minutes to complete. Any way to get a quick fix for this by rolling back the hypothesis version?

**Comment by Stranger6667** [comment]
I think the quickest way would be to install the previous Hypothesis version after installing Schemathesis. I will be able to address it properly either this evening or tomorrow

**Comment by phknot** [comment]
> I think the quickest way would be to install the previous Hypothesis version after installing Schemathesis. I will be able to address it properly either this evening or tomorrow

I'm using the official Github Action so that isn't so easy to do.

**Comment by Stranger6667** [comment]
Got it! I’ll fix the issue this evening. I think it would be better to shrink the class reprs so they don’t blow up even if the pretty printer will handle them eagerly on the Hypothesis side, ie it will be nice to have lazy evaluation there anyway, but it will be more reliable to minimise any possible impact, specifically as these reprs are not that useful for Schemathesis reportingitself
