### ISSUE TITLE
[FEATURE] Support examples as hypotheses

### ISSUE THREAD

**Issue by depopry** [schemathesis/schemathesis#2576]
### Is your feature request related to a problem? Please describe

I would like the ability to add  request examples to hypotheses to ensure there are accurate/valid tests conducted. This would reduce the amount of effort manually writing tests.

### Describe the solution you'd like

An additional flag in the CLI to instruct schemathesis to include examples in specs i.e. `--include-spec-examples`

### Describe alternatives you've considered

I'm not aware of any workarounds to accomplish this, other than manually writing tests.

**Comment by Stranger6667** [comment]
Hey! Yes, schemathesis parses examples from the spec and uses them in testing. Maybe the docs are lacking a good notion of this - right now I am working on Schemathesis 4 and will update the docs as well so they reflect it.
