### ISSUE TITLE
Schemathesis as a service

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#444]
It might be convenient to have a web interface to control test runs & results.

probably it can be in the same repo, but with extra dependencies:

```
pip install schemathesis[web]
```

Ideas
- `aiohttp` as a backend with OpenAPI;
- a pool of processes to run schemathesis there;
- WebSockets for realtime events displaying;
- UI to choose target and control schemathesis option;
- Storage for test run results & related data;
- Testing its API with schemathesis :recycle: 
- Scheduled runs

**Comment by aexvir** [comment]
> aiohttp as a backend with OpenAPI
Can I recommend FastAPI? It's a really well packaged solution for async web servers, taking OpenAPI at the core of it's development.

https://github.com/tiangolo/fastapi

**Comment by Stranger6667** [comment]
Thank you Alex, I'll definitely take a look :)

**Comment by Stranger6667** [comment]
It is great that they have moved away from `ujson`, it was bothering me for quite a long time

**Comment by Stranger6667** [comment]
As I started working on Schemathesis.io which basically a web interface to schemathesis with a lot of extra features, this task is not relevant at the moment.
