### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#500]
Based on #32 and discussion with @Hultner 

- [x] Have a smaller quickstart
- [x] Link to docs in the top of the page (not only badge)
- [x] Move documentation content to a separate document
- [ ] Share roadmap info
- [ ] Examples of errors that could be found
- [x] Details behavior of available checks
- [ ] Possible workflows for Schemathesis. As a part of a test suite, CI step, CLI, etc
- [ ] [Usage](https://github.com/untitaker/pytest-subtesthack) of `subtesthack` for pytest fixtures.
- [x] Add info about using regex in filters

We also can take inspiration from [Hypothesis docs](https://hypothesis.readthedocs.io/en/latest/quickstart.html)

**Comment by louisguitton** [comment]
+1 to adding the https://schemathesis.readthedocs.io/en/stable/ link to the github repo itself

**Comment by Stranger6667** [comment]
@louisguitton 

I moved the link slightly upper, hope that now it is more visible in the readme :) Let me know if I can provide more info on areas, that are interesting for you

**Comment by louisguitton** [comment]
hey @Stranger6667 nice thank you. I meant using the github feature of "URL to your project" if you see what I mean
![image](https://user-images.githubusercontent.com/7823843/88787663-81b96f80-d194-11ea-80e9-2c160835235a.png)

**Comment by Stranger6667** [comment]
Oh, I see. Unfortunately, I don't have admin access to this repo anymore. Maybe @aexvir could help with putting "https://schemathesis.readthedocs.io/en/stable/" to the "about" section?

**Comment by aexvir** [comment]
Added the info in the about section, and also gave you some permissions @Stranger6667 🙂 
Let me know if it's enough or if you need a higher access level

**Comment by Stranger6667** [comment]
Thank you @aexvir ! The permission level is OK :)
