### ISSUE TITLE
Open API link testing support for Pytest

### ISSUE THREAD

**Issue by philipp-sontag-by** [schemathesis/schemathesis#616]
I really like the new feature for testing the Open API links. It seems like it is currently only supported via the command line interface and not with Pytest. Will this be added in the future or am I missing a config option here?

**Comment by Stranger6667** [comment]
Hi @philipp-sontag-by 

> I really like the new feature for testing the Open API links

I am glad to hear that!

Indeed, you are right. It is currently not supported for Pytest, due to the original PR size. However, as most of the core things are already implemented (runtime expressions, stateful tests, etc) it shouldn't be a too big feature to implement in a single PR. I will take a look into this in the following weeks

**Comment by Stranger6667** [comment]
By the way, 

If you have any comments / suggestions on our Open API links implementation I'd like to hear them :) 
There are already some issues opened to extend this support - #603 #604

**Comment by philipp-sontag-by** [comment]
Sure, I will try it out in my next project and report back 👍

**Comment by david-vankampen** [comment]
@philipp-sontag-by curious - any progress on this? I too would like to run stateful (link-following) schemathesis tests within pytest.

**Comment by Stranger6667** [comment]
@david-vankampen 

FYI - currently, I am working on some internal refactorings that will enable easier pytest integration for "links" now and "inferred" approach (from #520) in the future. I'd estimate it for 2-3 weeks from now

**Comment by david-vankampen** [comment]
@Stranger6667 that sounds great.  From my perspective, the change on 520 for the pytest decorator accepting "stateful" as on optional argument would 100% meet the need.  Basically just the same capability that is currently on the command line, made available in pytest.

**Comment by david-vankampen** [comment]
@Stranger6667 any news here? Looking to incorporate stateful testing in a pytest suite.

**Comment by Stranger6667** [comment]
Hi @david-vankampen !

Unfortunately, there is no progress in this direction at the moment. I've been working mostly on organizational changes so that I can work on Schemathesis full-time. I hope that all things will settle down till October, and this issue is definitely on my TODO list :)

**Comment by Stranger6667** [comment]
This feature is implemented - I will release it in a few days together with #638 and I still need to do some more usability improvements to it.
