### ISSUE TITLE
Excluding certain test cases

### ISSUE THREAD

**Issue by lukasz-madon** [schemathesis/schemathesis#654]
I have an API with marshmallow validation. The problem is that it break if string is `.`

Case
```
self = Case(endpoint=Endpoint(path='/reviews/{reviewId}/comments', method='POST', definition=EndpointDefinition(raw={'tags': ...), path_parameters={'reviewId': 1}, headers=None, cookies=None, query=None, body={'': None, '.': None}, form_data=None)
response = <Response [500]>
```

Error
```
# https://marshmallow.readthedocs.io/en/stable/_modules/marshmallow/utils.html see set_value
ValueError: Cannot set . in  due to existing value: None
```

How to disable generating `.` ?

Global hook snippet is not correct here https://github.com/kiwicom/schemathesis/pull/356/files

EDIT: based on a closed issue the solution is:

```
import os

import schemathesis

from conftest import get_root_url

schema = schemathesis.from_path(
    os.path.join(os.path.dirname(__file__), "api_spec.yaml"), get_root_url()
)


@schema.hooks.register("before_generate_body")
def schema_hook(context, strategy):
    return strategy.filter(lambda x: "." not in str(x))


@schema.parametrize()
def test_no_server_errors(case, flask_test_app, cookies):
    # `requests` will make an appropriate call under the hood
    response = case.call(cookies=cookies)
    # You could use built-in checks
    case.validate_response(response)
    # Or assert the response manually
    assert response.status_code < 500
```

It's a bit restrictive since filters all values with `.` not just they keys.

**Comment by Stranger6667** [comment]
Hi @lukasz-madon,

Thank you for asking :) The general direction for such adjustments is to use hooks indeed!

> Global hook snippet is not correct here https://github.com/kiwicom/schemathesis/pull/356/files

This PR you are referring to is outdated and the current README doesn't contain it - the hooks system was working that way at the time when that PR was merged (except for the typo in the function name). The most up-to-date documentation on hooks is here - https://schemathesis.readthedocs.io/en/stable/customization.html

Regarding your exact case, I think that it would be better to explicitly check all keys in that dictionary (or other structure, depending on your schema - e.g. an array). Something like this:

```python
import schemathesis

@schemathesis.hooks.register
def before_generate_body(context, strategy):
    return strategy.filter(lambda x: "." not in x)
```

This should be sufficient for disabling `.` generation as a key of that dictionary.

Depending on your schema you could implement different kinds of filters there - that `x` could be of some other types so, keep it in mind. That example from the linked PR (that one with `str(x)`) is somehow misleading and I missed to provide some more verbose explanation on how filtering could be done. I'll update that section of our docs

Let me know if I can provide more info on this topic

**Comment by Stranger6667** [comment]
Hopefully, it answers your question :) If not, then feel free to reopen this issue or create a new one. Or reach me on [Gitter](https://gitter.im/kiwicom/schemathesis)
