### ISSUE TITLE
Add `--max-response-time` CLI option to verify the app response time

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#716]
A custom check that will fail if the response time is greater than the specified one.

**Implementation notes**
- Create a new option for the CLI app. It should have `int` type and will mean the time in milliseconds
- Pass it down to the `runner.impl.core.run_checks`
- Pass `elapsed_time` to `run_checks` as well
- If `max_response_time` is not empty and the elapsed time is greater than `max_response_time`, then create an `AssertionError` exception, add it to `errors` and call `result.add_failure` with proper arguments (similar to already existing call in that function). If the time is less, then call `result.add_success`
- Docs
- Changelog entry

NOTE. In the future, it could be just a generic check as, e.g. `not_a_server_error`, but it will require some refactoring and will imply backward-incompatible changes

**Comment by svtkachenko** [comment]
I guess I'll try this one.

**Comment by Stranger6667** [comment]
@svtkachenko Great! Let me know if the steps noted in the descriptions provide enough info to start implementation

**Comment by Stranger6667** [comment]
Thank you @svtkachenko for implementing this!
