### ISSUE TITLE
[BUG] Cannot handle multiple types

### ISSUE THREAD

**Issue by geekingfrog** [schemathesis/schemathesis#740]
**Describe the bug**
It seems schemathesis cannot handle situation where there are multiple possible types

**To Reproduce**

1. Run: `schemathesis run --base-url http://localhost:8888/ min-api.json`
2. Error:
```
An internal error happened during a test run
Error: jsonschema.exceptions.ValidationError: ['string', 'number'] is not of type 'string'

Failed validating 'type' in schema[0]['properties']['type']:
    {'enum': ['array', 'boolean', 'integer', 'number', 'object', 'string'],
     'type': 'string'}

On instance['type']:
    ['string', 'number']

Add this option to your command line parameters to see full tracebacks: --show-errors-tracebacks

You can disable input schema validation with --validate-schema=false command-line option
In this case, Schemathesis can not guarantee proper behavior during the test run

```

If possible, please post a minimal version of your API schema that cause this behavior:

```json
{
  "openapi": "3.0.2",
  "info": {
    "title": "mininum bug report example",
    "version": "0.0.1"
  },
  "paths": {
    "/test": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": [
                  "string",
                  "number"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "200 response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}


```

**Expected behavior**
This should work and post valid payload

**Environment (please complete the following information):**
 - OS: linux
 - Python version: 3.8
 - Schemathesis version: 2.4.1
 - Spec version: Open API 3.0.2

**Additional context**
I checked that `hypothesis-jsonschema` supports that, so it seems to be coming from schemathesis itself.

**Comment by Stranger6667** [comment]
Hi! Thank you for reporting this.

As per the [official swagger documentation](https://swagger.io/docs/specification/data-models/data-types/), this way of using multiple types is explicitly noted as incorrect.

```yaml
# Incorrect
type:
  - string
  - integer
```

And it suggests using `anyOf` or `oneOf` instead:

```yaml
# Correct
oneOf:
  - type: string
  - type: integer
```

The JSON schema we use to validate the input schemas is indeed points that `type` should be a string. It is different from the JSON schema behavior, which may be the cause of confusion. On the supported JSON Schema keywords [the doc says](https://swagger.io/docs/specification/data-models/keywords/):

> These keywords are supported with minor differences:
> type – the value must be a single type and not an array of types. null is not supported as a type, use the nullable: true keyword instead.

As the conclusion from my side - this behavior comes from the Open API spec, not from Schemathesis. Let me know if the proposed change fixes your case.

**Comment by geekingfrog** [comment]
Oops, sorry. You're right, I got mixed up between openAPI and json schema. That works with that.

**Comment by Stranger6667** [comment]
No problem! Feel free to open an issue or reach me on [Gitter](https://gitter.im/kiwicom/schemathesis) in case of any further questions :)
