### ISSUE TITLE
[BUG] Setting the "User-Agent" header may override the passed one

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#757]
**Describe the bug**

When the "User-Agent" header is set in `schemathesis/loaders.py` or `schemathesis/runner/impl/core.py`, it may override the header value when the request is sent.

**To Reproduce**
1. Pass `headers={"user-agent": "foo/1.0"}` to `schemathesis.from_uri`
2. The request is sent with the Schemathesis user agent

**Expected behavior**
If the user agent header passed explicitly, then it should not be overridden by Schemathesis.

I.e,. we need to use case-insensitive dictionaries for headers handling

**Comment by hebertjulio** [comment]
#781

**Comment by Stranger6667** [comment]
Done in #781. Thanks, @hebertjulio !

**Comment by hebertjulio** [comment]
No problem :)
