### ISSUE TITLE
Verify headers schema in the response_headers_conformance check

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#796]
Now schemathesis only checks if a header is present, but can actually check schema conformance as well

**Comment by basbossink-ds** [comment]
It appears currently also _missing_ headers are reported as an error even if the schema specifies the header as _optional_.

**Comment by Stranger6667** [comment]
Hi @basbossink-ds 

Good catch! Let me fix it :)

**Comment by Stranger6667** [comment]
That issue is going to be fixed in #1564. I'll release a new version during this week
