### ISSUE TITLE
[FEATURE] Improve testing of Case.as_curl_command method

### ISSUE THREAD

**Issue by zhukovgreen** [schemathesis/schemathesis#807]
**Is your feature request related to a problem? Please describe.**
Ref #689 
The feature is a follow-up task from #689.
The current implementation of `Case.as_curl_comand` has a very basic test coverage, which could mean it is fragile and not validated well yet.

**Describe the solution you'd like**
Implement a test suite that tests the curl command generation for all possible cases available in OpenAPI schema.
Current feature implementation can be found here:
https://github.com/schemathesis/schemathesis/pull/806/files

**Additional context**
Possibly useful information:
- https://github.com/schemathesis/schemathesis/issues/689#issuecomment-707495922
- decorator for generating all endpoints `@pytest.mark.endpoints("__all__")`

**Comment by Stranger6667** [comment]
As an additional idea for testing `curlify` itself:

- generate requests with hypothesis strategy 
- make requests to httpbin (e.g. via `pytest-httpbin` to avoid external network)
- Convert request to cURL and make a request to the local httpbin
- Compare two responses - they should be very similar (except time, and maybe some tool-specific headers)

It might be slightly out of scope for Schemathesis, but it might give more confidence that all requests will be converted properly
