### ISSUE TITLE
[BUG] responses missing content-type pass response_schema_conformance/content_type_conformance

### ISSUE THREAD

**Issue by ysangkok** [schemathesis/schemathesis#816]
**Describe the bug**
if you call `schemathesis.models.Case.validate_response` with a response that has no content-type (see below), it will swallow the KeyError and just return early:

```
def response_schema_conformance(response: GenericResponse, case: "Case") -> None:
    if not isinstance(case.endpoint.schema, BaseOpenAPISchema):                 
        raise TypeError("This check can be used only with Open API schemas")       
    try:                                                                        
        content_type = response.headers["Content-Type"]                         
    except KeyError:                                                            
        # Not all responses have a content-type                                 
        return
```

**To Reproduce**
call `validate_response(resp, (response_schema_conformance,))` on a response that has no content-type

**Expected behavior**
a reply missing the content-type should fail the conformance check unconditionally

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.9.0rc2
 - Schemathesis version: 2.6.1
 - Spec version: 3.0.0

**Additional context**
```
> /home/janus/.pyenv/versions/3.9.0rc2/lib/python3.9/site-packages/schemathesis/specs/openapi/checks.py(84)response_schema_conformance()
-> content_type = response.headers["Content-Type"]
(Pdb) p response.headers
{'server': 'Rocket', 'content-length': '152', 'date': 'Tue, 20 Oct 2020 20:00:08 GMT'}
(Pdb) 
```

**Comment by Stranger6667** [comment]
Hi @ysangkok ! 

Thank you for reporting this. I will take a look tomorrow :) it seems easy to fix

**Comment by ysangkok** [comment]
I just noticed now that there is a `content_type_conformance` checker, which is the reason why the `response_schema_conformance` checker simply ignores. By this other checker also ignores responses with missing content-types. Maybe it is more correct to consider the bug as being there, so I changed the title...

**Comment by Stranger6667** [comment]
I think I overlooked this behavior initially - If we received a response that we know should have one of the defined content-types, then if it has no content type it is an error. I will change this behavior and will issue a release today / tomorrow. Thank you again for reporting this

**Comment by yobiscus** [comment]
What is the desired behaviour for a 204 No Content response? According to [RCF2616 section 7.2.1](https://tools.ietf.org/html/rfc2616#section-7.2.1), "any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body." Conversely, the RFC does not suggest anywhere that an HTTP response _without_ an entity-body is required to include a Content-Type.

**Comment by Stranger6667** [comment]
@yobiscus 

Good question! 

For the `content_type_conformance` check:

I think if the schema defines expected media types, then it should be required. If not - then the check is skipped (as it is now). 

However, the Open API 3 spec says nothing if it should be applied strictly, or the response could have other media types that are not specified in the list (or no content type). For this reason, the check is optional - if one would like to check that the response media type always matches one from the list of defined media types. Then the check can be enabled.

For the `response_schema_conformance` check:

It should be the same, but now the "Content-Type" header presence check works before checking if there are any defined media types at all. And I'd like to change it to allow the case when there is no header defined in the schema and the received response.

**Comment by yobiscus** [comment]
@Stranger6667 thanks for the detailed response. The error during `response_schema_conformance` check is what prompted my question:

```
response_schema_conformance                     12 / 20 passed          FAILED
1. Response is missing the `Content-Type` header
```

> And I'd like to change it to allow the case when there is no header defined in the schema and the received response.

That would be great! Should I open a new issue against this?

**Comment by Stranger6667** [comment]
Sorry for the delay! I created #844 to track it :)
