### ISSUE TITLE
[FEATURE] Add documentation on the differences between Schemathesis and Dredd

### ISSUE THREAD

**Issue by uta-mori** [schemathesis/schemathesis#817]
**Is your feature request related to a problem? Please describe.**
The differences with Dredd may not be immediately apparent.

**Describe the solution you'd like**
Add the answer to this question to the FAQ on the documentation site

[Nice article, and useful tool :). Just wondered: 1. The user has to… | by Richard Waller | Medium](https://medium.com/@richard.lh.waller/nice-article-and-useful-tool-b7bdee5cb9dd)

> The biggest difference that I see is that Dredd is using examples and defaults from the schema (I might be wrong but it refuses to run until I add them to the spec under test), Schemathesis generates test cases + uses examples as separate test cases. Also, Schemathesis provides test case shrinking (i.e finding the minimal failing example). I’d say that there are a lot of features that Dredd does that are not in Schemathesis (e.g. API Blueprint support, that powerful hook system, and many more) and probably vice versa. I think we can learn a lot from Dredd, it is an important tool :)

**Comment by Stranger6667** [comment]
Hi @uta-mori !

Sure thing, I will add this info to the FAQ section today :)

**Comment by Stranger6667** [comment]
Resolved via https://github.com/schemathesis/schemathesis/commit/8ebe3e5200b0d00e287a1e118c02644739290c09
