### ISSUE TITLE
[FEATURE] Exclude endpoints

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#819]
**Is your feature request related to a problem? Please describe.**
It is complicated to exclude endpoints from testing. E.g. if you want to exclude one endpoint then you either need to use `pytest -k "not ..."` syntax, or some complex regular expression or compose the testing using only the "include" direction

**Describe the solution you'd like**
Maybe arguments that will exclude endpoints from testing. Not sure for now

**Comment by dwreeves** [comment]
Something like this maybe for the implementation? Let me know your thoughts.

### `schemathesis/specs/openapi/filters.py`

```python
def _match_any_pattern(target: str, include_patterns: Optional[Filter], exclude_patterns: Optional[Filter] = None) -> bool:
    _force_tuple = lambda p: None if p is None else force_tuple(p)
    _match_pat = lambda t, p, default: default if not p else any(re.search(i, t) for i in p)

    include_patterns = _force_tuple(include_patterns)
    exclude_patterns = _force_tuple(exclude_patterns)
    return _match_pat(target, include_patterns, True) and not _match_pat(target, exclude_patterns, False)
```

Then change `should_skip_endpoint` to take similar arguments. Because the signature changes here and takes optional args, we no longer need to use `if _ is None:` in `should_skip_endpoint`.

### `schemathesis/specs/openapi/schemas.py`

In `BaseOpenAPISchema.get_all_endpoints`, update call to `should_skip_endpoint` to pass both `include_patterns=self.endpoint` and `exclude_patterns=self.exclude_endpoint`.

### `schemathesis/schemas.py`

Update `BaseSchema` to take a `exclude_endpoint` attribute with the same signature as the existing `endpoint` attribute.

### Other

Need to update this in a lot more places such as lazy.py and the cli module.

**Comment by Stranger6667** [comment]
Hi @dwreeves !

Indeed, gathering filtering logic like this makes sense to me :) However, I am mostly concerned about the high-level API. At the moment, I am inclined to use chaining (like iterator's API in Rust):

```python
schema = schemathesis.from_uri(
    ...
).include(
    method="POST",
).exclude(
    tag="auth"
)
```

The approach with different argument names doesn't seem that ergonomic to me, e.g., having "exclude_"  prefixes for each filtering option will lead to 8 different arguments to `parametrize`. However, the chaining approach won't work in decorators on Python < 3.9, so I am not sure about it :( 

I plan to do some experiments for this next week or so since I need this feature for Schemathesis IO. I'll post an update here as soon as I have more info.

**Comment by dwreeves** [comment]
For Python < 3.9 you can just have users define a decorator at the module scope. It loses a bit of its elegance admittedly, but not sure what else to do about < 3.9:

```python
from functools import wraps


class ParametrizeDecorator:

    def __call__(self, *args, **kwargs):
        raise NotImplementedError

    def include(self, endpoint: str) -> callable:
        raise NotImplementedError

    def exclude(self, endpoint: str) -> callable:
        raise NotImplementedError

class Schema:
    include_endpoints = []
    exclude_endpoints = []
    def parametrize(self):

        def wrapped(func: callable = None):
            @wraps(func)
            def execute_test():
                print('executing...')
                print('including these:', self.include_endpoints)
                print('excluding these:', self.exclude_endpoints)

            return execute_test

        def include(endpoint: str) -> ParametrizeDecorator:
            self.include_endpoints.append(endpoint)
            return wrapped

        def exclude(endpoint: str) -> ParametrizeDecorator:
            self.exclude_endpoints.append(endpoint)
            return wrapped

        wrapped: ParametrizeDecorator
        wrapped.include = include
        wrapped.exclude = exclude
        return wrapped


# Python < 3.9 implementation:

schema = Schema()
schema_test = schema.parametrize().include('asdf').exclude('jkl;')


@schema_test
def hello():
    return 'world'

if __name__ == '__main__':
    print(hello())
```
