### ISSUE TITLE
[BUG] Lowercase HTTP headers are not supported

### ISSUE THREAD

**Issue by Edward-Knight** [schemathesis/schemathesis#833]
**Describe the bug**
Schemathesis expects headers with a certain case. I came across this when upgrading from 2.6.1 to 2.7.0, where this change was introduced:
https://github.com/schemathesis/schemathesis/commit/9bcc3cdab3a57bc8a89db3d815da0465d815e98f
https://github.com/schemathesis/schemathesis/blob/9bcc3cdab3a57bc8a89db3d815da0465d815e98f/src/schemathesis/specs/openapi/checks.py#L52-L54

HTTP headers are not case sensitive (emphasis mine):
https://tools.ietf.org/html/rfc7230#section-3.2
> Each header field consists of a _case-insensitive_ field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.

**To Reproduce**
I don't have a simple reproduction with an API schema, but the `uvicorn` hello world example can be used as a test server: https://www.uvicorn.org/#quickstart

**Expected behavior**
Schemathesis should not fail tests when headers are sent in lowercase, or any other case.

**Environment:**
 - OS: macOS Mojave and Ubuntu Xenial
 - Python version: 3.7.9
 - Schemathesis version: 2.6.1 (working), 2.7.0 and 2.7.1 (not working)
 - Spec version: Unsure (using auto-generated spec from [FastAPI](https://fastapi.tiangolo.com/))

**Comment by Stranger6667** [comment]
Hi @Edward-Knight,

> Schemathesis expects headers with a certain case

The underlying structure for `response.headers` is either `requests.structures.CaseInsensitiveDict` or `werkzeug.datastructures.Headers` which both work as case-insensitive mappings. 

Is there any concrete use-case when it fails the check because of this reason?

**Comment by Stranger6667** [comment]
It might be related to this comment, though - https://github.com/schemathesis/schemathesis/issues/816#issuecomment-717395086

What status code does your endpoint return?

**Comment by Stranger6667** [comment]
Doesn't seem valid as per my comment above. If you have any concerns, feel free to reopen.
