### ISSUE TITLE
[BUG] requestBody with text/plain gets wrapped in quotes when sent to server

### ISSUE THREAD

**Issue by rtyler** [schemathesis/schemathesis#850]
**Describe the bug**

When specifying a request body as just a plain string, the request that is sent to the server is wrapped with double-quotes rather than the raw string being sent.

**To Reproduce**

1. Use the spec below
1. Hit a simple server endpoint that just dumps the request body (mine is in rust, so not that helpful)
1. Observe the data being wrapped in quotes.

```yaml
---
openapi: 3.0.0
info:
  title: Service
  version: '1.0.0'
paths:
  '/v1/parse':
    post:
      operationId: ParsePipeline
      requestBody:
        description: Pipeline syntax
        content:
          text/plain:
            schema:
              type: string
            examples:
              success:
                summary: 'Legit'
                value: 'hello world'

      responses:
        '200':
          description: Successfully parsed
```

**Expected behavior**

The raw string would be what I expected for sure :smile_cat:

**Environment (please complete the following information):**
 - OS:  Linux
 - Python version: 3.8.5
 - Schemathesis version: 2.7.1

**Additional context**

It looks like the use of `is_multlpart` in the `Case` class is the culprit here, since a plain string is viewed as "not" multipart and as such passed to `requests` as a `json` payload, rather than a `data` keyword argument.

I'm not sure what the right solution here is however. Monkey-patching such that a `str` body type is sent to requests as `data` definitely solves the problem but I'm sure that will have unintended consequences for other data types.

FWIW the swagger editor takes the above spec and sends the raw `hello world` string along to the server as I would expect

**Comment by Stranger6667** [comment]
Hi @rtyler !

Thank you for the detailed report! :) 

> It looks like the use of is_multlpart in the Case class is the culprit here, since a plain string is viewed as "not" multipart and as such passed to requests as a json payload, rather than a data keyword argument.

Currently we handle only `application/json`, `multipart/form-data` and `application/x-www-form-urlencoded` :( There are long-term plans to generate data for more media types (#690 and #697 ) and allow users to register their own strategies. However, it might be better to explicitly fail on an unknown media type (or skip it and keep only explicit examples) rather than handling it like it is now (there is probably an `else` branch somewhere)

I will change the code, so plain text data is not encoded as JSON :)

**Comment by Stranger6667** [comment]
Hm, probably the most straightforward way to send generated payload would be like this (from the highest priority):
1. Send forms if they are defined
2. then check if the tested operation expects `application/json` (and variations) and use the  `json` keyword
3. use the `data` keyword and add the expected 'content-type' header value

I.e., if Schemathesis generated some payload, then it knows how to do it, and it should be ok to send it this way. However, I'll check for more corner cases anyway

**Comment by Stranger6667** [comment]
Now it should work with the "latest" Docker image :) I still need to add more changes before a stable release, but it should already be possible to test operations with the `text/plain` media type.

Let me know if it doesn't cover your use case (it should - I added a couple of test cases for it).

Sorry for the delay!
