### ISSUE TITLE
[FEATURE] Throttle the outgoing requests

### ISSUE THREAD

**Issue by niecore** [schemathesis/schemathesis#910]
**Is your feature request related to a problem? Please describe.**
I want to use `schemathesis` on a slow server. It seems like when I run the tests, the server can not process all requests and starts sending `500` code responses.

**Describe the solution you'd like**
Would it be possible to add sleep time in between the test cases?

**Comment by Stranger6667** [comment]
Hi! Thank you for requesting this!

There is #704, which is scoped to CLI, but I think it may work in the Python context as well, so I close that issue in favor of this one :)

**Comment by Stranger6667** [comment]
In the meanwhile, I suggest adding [this hook](https://schemathesis.readthedocs.io/en/stable/extending.html#add-case) with an implementation like this one:

```python
# Let say this is `tests/hooks.py` file
import time
import schemathesis


@schemathesis.hooks.register
def add_case(context, case, response):
    time.sleep(0.5)
    return None
```

And it can be loaded to CLI like this (assuming `tests/hooks.py` is importable):

```
schemathesis --pre-run tests.hooks run ...
```

It will wait 500ms after each call :) But, the built-in feature for throttling for sure will be implemented.

**Comment by niecore** [comment]
Thanks a lot!

**Comment by Stranger6667** [comment]
You are welcome! :) I'd like to keep this issue open since it is broader than the old one :)

**Comment by Stranger6667** [comment]
Some time ago I implemented throttling in Schemathesis.io (but never actually exposed it), so, now I'd like to open source it as a part of Schemathesis.

It is implemented as a hook on top of `PyrateLimiter`, and is applicable only to CLI / runner - for python tests, I'd expect the user to use `PyrateLimiter` or any other solution directly.

Possible usage example:
- `--rate-limit=10/m` - force Schemathesis to execute 10 requests per minute at most
- `--rate-limit=2/s` - 2 requests per second

Not sure about the option name, maybe there could be other places we'd like to limit, but if not, then `--rate-limit` is probably the most obvious (got to check how other projects do it, e.g. `locust`)
