### ISSUE TITLE
[FEATURE] A way to refresh auth

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#966]
**Is your feature request related to a problem? Please describe.**
Currently, if the auth token expires during the test run, there is no built-in way to refresh it. It will be nice to have some way to register a function that will refresh auth. And maybe some refresh interval

**Describe the solution you'd like**
A decorator that will register such a function that will return headers required for authorization

**CLI implementation notes**

Here are my thoughts about implementing this feature.

It might look like this for the end-user - [similar](https://schemathesis.readthedocs.io/en/stable/cli.html#extending-cli) to other hooks:

```python
import schemathesis


@schemathesis.register_auth_provider(refresh_interval=600)  # in seconds
def auth_provider(auth: AuthStorage):
    response = requests.post(...)
    token = response.json()["access_token"]
    ...  # Set the auth
```

This decorator may store the function & refresh period in some global variable (it is global for a run anyway) that will be available for the Schemathesis internals.

Then whenever Schemathesis [makes a network call](https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/runner/impl/core.py#L544) (or [WSGI](https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/runner/impl/core.py#L637) / [ASGI](https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/runner/impl/core.py#L725) calls) we check whether we need to call this function (depending on the time since the last auth function call + some leeway) and call it on some longer-lived storage for auth. E.g. we might need to put the auth into query params or into headers (usually it is the case). This might require some small object that will allow the user to set the auth according to their needs. Then we can properly set the auth in those network calls. It might be something like:

```python
# Schemathesis internals
class AuthStorage:
    ...  # attrs for storing query / header values

    def set_query(self, name: str, value: str) -> None
        self.query[name] = value
    ...  # similarly for other auth types
...
# End-user code

@schemathesis.register_auth_provider(...)
def set_auth(auth: AuthStorage):
    ...  # get the token
    auth.set_query("api_token", token)

# Adjust network calls
def _network_test(case, ..., auth: Optional[AuthStorage]):
    if auth is not None:
        set_auth(case, auth)  # Calls the auth provider function if needed
    ...  # make the call
```

This storage lifetime is bound to the runner, so it could be initialized somewhere [here](https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/runner/impl/core.py#L76). Also, I think some parts of the code above surely could be factored out into something more isolated.

Keep in mind, that it requires synchronization as it could be accessed from multiple threads (e.g. lock over accessing the auth)

**Python test implementation notes**

It might be similar in Python tests. E.g., the end-user registers some auth provider on the `schema` object or globally:

```python
schema = ...

# Creates a pytest fixture that provides a single `set_auth` method.
@schema.register_auth_provider(refresh_interval=600)
def auth(auth_storage):
    ...


@schema.parametrize()
def test_api(case, auth):
    auth.set_auth(case)  # Does all the stuff under the hood
```

**Comment by JangasCodingplace** [comment]
I would like to participate to that challenge!
Have no experience with your tool yet, but like your project from a high level point of view.

I am an experienced Python Dev and am working full-time in Data & Backend Engineering. We'll see if I am the right match for that issue.

If you gonna assign me to that ticket, I will start working on that latest at Monday

**Comment by Stranger6667** [comment]
Hi @JangasCodingplace !

Awesome! Nice to e-meet you :) I will provide more details during the weekend

**Comment by JangasCodingplace** [comment]
Cool! Thanks a lot and keep your time. ✌️😊

**Comment by Stranger6667** [comment]
Hej @JangasCodingplace ! I updated the description with a few thoughts of how it might be implemented :) I'd be happy to elaborate

I'll add a more concrete action list later

**Comment by JangasCodingplace** [comment]
Hey @Stranger6667 sorry for delay, I am starting now and try to get an overview first

**Comment by JangasCodingplace** [comment]
Thanks for all your advices

**Comment by JangasCodingplace** [comment]
Could you give me a quick code Snippet of how you currently implement an authentication?
It's not about solving the issue, it's an example:

imagine there is a single test which requires an authentication token.
How would you currently implement it without refreshing?

I am finally able to debug everything in PyCharm and have used poetry for project setup.
Now I need to find an entry point into that project for being able to understand the issue and implement a solution.
Therefor an example with all of the **current** best practices by the project master himself would be very useful ;-)

Something like that example would be already enough:
https://github.com/schemathesis/schemathesis/blob/master/test/code_samples/test_python.py#L56

**Comment by JangasCodingplace** [comment]
My Draft:
https://github.com/schemathesis/schemathesis/pull/1295

Please make a high level review. I haven't look at black formatting and listing yet. Will do it as soon as I finalise the project.
Before I spent more time into it, a first high-level review would be nice

Thanks a lot!

**Comment by Stranger6667** [comment]
@JangasCodingplace Thanks, I'll reply tomorrow morning :)
